import { useEffect, useMemo, useRef, useState } from 'react';
import { Database, FileJson2, FileSpreadsheet, Trash2, Upload } from 'lucide-react';
import { CsvDataSourceAdapter } from '@document-tool/datasource-csv';
import { ExcelDataSourceAdapter } from '@document-tool/datasource-excel';
import type { FieldDefinition, NormalizedRecord, NormalizedValue } from '@document-tool/contracts';
import type { SourceFileInput } from '@document-tool/datasource-sdk';
import { PageHeader } from '../components/PageHeader.tsx';
import { RecordPicker } from '../components/RecordPicker.tsx';
import { activeSource, loadDataState, loadDataStateAsync, saveDataSelection, saveDataState, type BuilderDataSource, type BuilderDataState } from '../lib/dataSourceStore.ts';

export function DataSources() {
  const [state, setState] = useState<BuilderDataState>(() => loadDataState());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [jsonText, setJsonText] = useState('');
  const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { void loadDataStateAsync().then(setState).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load local data sources.')); }, []);
  const source = activeSource(state);
  const selectedRecordIndex = source ? Math.min(Math.max(0, state.activeRecordIndex), Math.max(0, source.records.length - 1)) : 0;
  const selectedRecord = source?.records[selectedRecordIndex] ?? null;
  const previewStart = source ? Math.max(0, Math.min(selectedRecordIndex - 3, Math.max(0, source.records.length - 8))) : 0;
  const previewRows = useMemo(() => source?.records.slice(previewStart, previewStart + 8) ?? [], [source, previewStart]);
  async function persist(next: BuilderDataState) { setState(next); try { await saveDataState(next); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to persist the data source.'); } }
  async function importFile(file: File) { setBusy(true); setError(''); try { const extension = file.name.split('.').pop()?.toLowerCase() ?? ''; const input: SourceFileInput = { name: file.name, extension, size: file.size, bytes: await file.arrayBuffer() }; let nextSource: BuilderDataSource; if (extension === 'csv') { const adapter = new CsvDataSourceAdapter(); const data = await adapter.getData({ sourceOptions: { file: input } }); nextSource = toSource(file.name, 'csv', data.schema.fields, data.records, data.warnings?.map((w) => w.message) ?? []); } else if (extension === 'xlsx' || extension === 'xls') { const adapter = new ExcelDataSourceAdapter(); const inspection = adapter.inspect(input); const data = await adapter.getData({ sourceOptions: { file: input, sheetName: inspection.defaultSheetName, headerRow: inspection.suggestedHeaderRow } }); nextSource = { ...toSource(file.name, 'excel', data.schema.fields, data.records, data.warnings?.map((w) => w.message) ?? []), sheetName: inspection.defaultSheetName }; } else throw new Error('Choose a .csv, .xlsx or .xls file. JSON can be pasted below.'); await persist({ sources: [nextSource, ...state.sources], activeSourceId: nextSource.id, activeRecordIndex: 0 }); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to import this file.'); } finally { setBusy(false); } }
  async function importJson() { setError(''); try { const parsed: unknown = JSON.parse(jsonText); const rows = Array.isArray(parsed) ? parsed : [parsed]; const records = rows.filter((row): row is Record<string, unknown> => Boolean(row) && typeof row === 'object' && !Array.isArray(row)).map(normalizeJsonRecord); if (records.length === 0) throw new Error('JSON must contain an object or an array of objects.'); const fields = inferJsonFields(records); const nextSource = toSource(`JSON ${new Date().toLocaleTimeString()}`, 'json', fields, records, []); await persist({ sources: [nextSource, ...state.sources], activeSourceId: nextSource.id, activeRecordIndex: 0 }); setJsonText(''); } catch (err) { setError(err instanceof Error ? err.message : 'Invalid JSON.'); } }
  function deleteSource(id: string) { const sources = state.sources.filter((item) => item.id !== id); void persist({ sources, activeSourceId: sources[0]?.id ?? null, activeRecordIndex: 0 }); }
  return <div className="page"><PageHeader eyebrow="Data" title="Data Sources" description="Import Excel, CSV or JSON, inspect detected fields, and use records for live template binding." />
    <section className="data-source-layout"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">DB-3</span><h2>Import source</h2></div>{source && <span className="status-pill">{source.records.length} records</span>}</div><div className="drop-zone data-drop" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); const file = e.dataTransfer.files[0]; if (file) void importFile(file); }}><Upload size={30}/><strong>Drop Excel or CSV here</strong><span>.xlsx, .xls and .csv are parsed by the retained datasource engines.</span><input ref={fileInput} type="file" accept=".csv,.xlsx,.xls" hidden onChange={(e) => { const file = e.target.files?.[0]; if (file) void importFile(file); e.currentTarget.value = ''; }}/><button className="secondary" disabled={busy} onClick={() => fileInput.current?.click()}>{busy ? 'Importing…' : 'Choose file'}</button></div><div className="json-import"><div className="json-title"><FileJson2 size={18}/><strong>Paste JSON</strong></div><textarea value={jsonText} onChange={(e) => setJsonText(e.target.value)} placeholder='[{"Name":"Akash","Id":"EMP001"}]'/><button className="secondary" disabled={!jsonText.trim()} onClick={() => void importJson()}>Import JSON</button></div>{error && <div className="error-banner">{error}</div>}</div>
      <div className="panel source-list-panel"><h2>Imported sources</h2>{state.sources.length === 0 ? <div className="empty-state"><Database size={26}/><strong>No source imported</strong><span>Import a file or paste JSON to create a reusable local data source.</span></div> : <div className="source-list">{state.sources.map((item) => <div key={item.id} className={item.id === state.activeSourceId ? 'source-card active' : 'source-card'} onClick={() => { const next = { ...state, activeSourceId: item.id, activeRecordIndex: 0 }; setState(next); saveDataSelection(next); }}><span className="source-icon">{item.sourceType === 'json' ? <FileJson2 size={18}/> : <FileSpreadsheet size={18}/>}</span><span><strong>{item.name}</strong><small>{item.sourceType.toUpperCase()} • {item.fields.length} fields • {item.records.length} records{item.sheetName ? ` • ${item.sheetName}` : ''}</small></span><button title="Delete source" onClick={(e) => { e.stopPropagation(); deleteSource(item.id); }}><Trash2 size={15}/></button></div>)}</div>}</div></section>
    {source && <section className="panel data-preview-panel"><div className="panel-heading"><div><span className="eyebrow">Active source</span><h2>{source.name}</h2></div><label className="record-picker">Preview record <RecordPicker count={source.records.length} value={state.activeRecordIndex} compactLabel="Record" onChange={(index) => { const next = { ...state, activeRecordIndex: index }; setState(next); saveDataSelection(next); }}/></label></div><div className="field-chips">{source.fields.map((field) => <span key={field.name}><b>{field.label}</b><small>{field.type}</small></span>)}</div>{source.warnings.length > 0 && <div className="warning-list">{source.warnings.map((warning, i) => <span key={i}>{warning}</span>)}</div>}{selectedRecord && <div className="selected-record-preview"><div><span className="eyebrow">Selected record</span><strong>Record #{selectedRecordIndex + 1}</strong></div><div className="selected-record-fields">{source.fields.slice(0, 8).map((field) => <span key={field.name}><small>{field.label}</small><b>{renderCell(selectedRecord[field.name]) || '—'}</b></span>)}</div></div>}<div className="data-table-wrap"><table className="data-table"><thead><tr><th>#</th>{source.fields.map((field) => <th key={field.name}>{field.label}</th>)}</tr></thead><tbody>{previewRows.map((row, index) => { const absoluteIndex = previewStart + index; return <tr key={absoluteIndex} className={absoluteIndex === selectedRecordIndex ? 'selected-preview-row' : ''}><td>{absoluteIndex + 1}</td>{source.fields.map((field) => <td key={field.name}>{renderCell(row[field.name])}</td>)}</tr>; })}</tbody></table></div><small className="preview-note">Showing records {previewStart + 1}–{Math.min(previewStart + previewRows.length, source.records.length)} of {source.records.length}. Record #{selectedRecordIndex + 1} is shared with Template Builder.</small></section>}
  </div>;
}
function toSource(name: string, sourceType: BuilderDataSource['sourceType'], fields: FieldDefinition[], records: NormalizedRecord[], warnings: string[]): BuilderDataSource { return { id: crypto.randomUUID(), name, sourceType, fields, records, warnings, importedAt: new Date().toISOString() }; }
function normalizeJsonRecord(input: Record<string, unknown>): NormalizedRecord { const result: NormalizedRecord = {}; for (const [key, value] of Object.entries(input)) result[key] = normalizeJsonValue(value); return result; }
function normalizeJsonValue(value: unknown): NormalizedValue { if (value == null || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') return value as string | number | boolean | null; if (Array.isArray(value)) return value.map(normalizeJsonValue); if (typeof value === 'object') return normalizeJsonRecord(value as Record<string, unknown>); return String(value); }
function inferJsonFields(records: NormalizedRecord[]): FieldDefinition[] { const names = Array.from(new Set(records.flatMap((record) => collectFieldPaths(record)))); return names.map((name) => { const values = records.map((record) => readPath(record, name)).filter((v) => v != null); const first = values[0]; const type: FieldDefinition['type'] = Array.isArray(first) ? 'array' : typeof first === 'object' ? 'object' : typeof first === 'number' ? 'number' : typeof first === 'boolean' ? 'boolean' : 'string'; return { name, label: name, originalLabel: name, type, required: records.every((record) => readPath(record, name) != null), nullable: records.some((record) => readPath(record, name) == null) }; }); }
function collectFieldPaths(record: NormalizedRecord, prefix = ''): string[] { const result: string[] = []; for (const [key, value] of Object.entries(record)) { const path = prefix ? `${prefix}.${key}` : key; if (value && typeof value === 'object' && !Array.isArray(value)) result.push(...collectFieldPaths(value as NormalizedRecord, path)); else result.push(path); } return result; }
function readPath(record: NormalizedRecord, path: string): NormalizedValue | undefined { let current: NormalizedValue | undefined = record; for (const part of path.split('.')) { if (!current || typeof current !== 'object' || Array.isArray(current)) return undefined; current = (current as NormalizedRecord)[part]; } return current; }
function renderCell(value: NormalizedValue | undefined) { if (value == null) return ''; if (typeof value === 'object') return JSON.stringify(value); return String(value); }
