import{describe,expect,it}from'vitest';import type{TemplateDefinition}from'@document-tool/contracts';import{ExportCancellationSource,ExportCancelledError,ExportOrchestrator,RendererRegistry}from'@document-tool/renderer-sdk';import{flattenRgba,JpegRenderer,registerJpegRenderer,type JpegEncoder,type PhysicalPageRasterizer,type RasterPage}from'../src/index.js';
const template={id:'jpeg',name:'JPEG',version:1,page:{size:'A4',orientation:'LANDSCAPE',margins:{top:10,right:10,bottom:10,left:10}},header:{blocks:[]},body:{blocks:[]},footer:{blocks:[]}}satisfies TemplateDefinition;const document={documentGroupId:'a',template,model:{variables:{amount:'₹47.20'},page:template.page,body:[]}};
class Rasterizer implements PhysicalPageRasterizer{calls:number[]=[];constructor(private count=2,private cancel?:()=>void){}async getPageCount(){return this.count;}async rasterizePage(_document:typeof document,page:number,width:number,height:number):Promise<RasterPage>{this.calls.push(page);this.cancel?.();const rgba=new Uint8Array(width*height*4);rgba.set([255,0,0,128]);return{width,height,rgba};}}
class Encoder implements JpegEncoder{inputs:Array<{rgb:Uint8Array;quality:number;width:number;height:number}>=[];async encode(width:number,height:number,rgb:Uint8Array,quality:number){this.inputs.push({rgb,quality,width,height});return new Uint8Array([255,216,quality,255,217]);}}
const token={isCancellationRequested:false,throwIfCancellationRequested(){}};
describe('Phase 4.19.3 JPEG renderer',()=>{
it('registers JPEG, exports all pages, flattens alpha, and reports diagnostics',async()=>{const registry=new RendererRegistry(),rasterizer=new Rasterizer(),encoder=new Encoder();registerJpegRenderer(registry,rasterizer,encoder);const result=await new ExportOrchestrator({registry,resolveDocument:async(_t,id)=>({...document,documentGroupId:id})}).export({format:'JPEG',templateId:'jpeg',documentGroupIds:['a'],fileName:'JPEG',options:{jpeg:{dpi:96,quality:90,backgroundColor:'#FFFFFF'}}});expect(registry.capabilities('JPEG').supportsTransparency).toBe(false);expect(result.files.map(file=>file.fileName)).toEqual(['JPEG_page_001.jpg','JPEG_page_002.jpg']);expect(result.files[0]!.mimeType).toBe('image/jpeg');expect(encoder.inputs[0]!.rgb.slice(0,3)).toEqual(new Uint8Array([255,127,127]));expect(result.diagnostics).toMatchObject({dpi:96,quality:90,backgroundColor:'#FFFFFF',pageCount:2});});
it('supports custom backgrounds and exact alpha compositing',()=>{expect(flattenRgba(new Uint8Array([0,0,255,0,255,0,0,255]),{r:247,g:244,b:237})).toEqual(new Uint8Array([247,244,237,255,0,0]));});
it.each([0,30,59,101,120,Number.NaN])('rejects invalid quality %s',async quality=>{await expect(new JpegRenderer(new Rasterizer(),new Encoder()).render({document,fileName:'bad',options:{jpeg:{quality}},cancellationToken:token})).rejects.toThrow(/quality/);});
it('rejects invalid background before rasterizing',async()=>{const rasterizer=new Rasterizer();await expect(new JpegRenderer(rasterizer,new Encoder()).render({document,fileName:'bad',options:{jpeg:{backgroundColor:'white'}},cancellationToken:token})).rejects.toThrow(/background color/);expect(rasterizer.calls).toHaveLength(0);});
it('exports the explicit current page and propagates DPI',async()=>{const rasterizer=new Rasterizer(3),encoder=new Encoder();const result=await new JpegRenderer(rasterizer,encoder).render({document,fileName:'current',options:{jpeg:{pageSelection:'CURRENT',currentPageIndex:1,dpi:150}},cancellationToken:token});expect(result.files[0]!.fileName).toBe('current_page_002.jpg');expect(rasterizer.calls).toEqual([1]);expect(encoder.inputs[0]).toMatchObject({quality:90,width:1754,height:1240});});
it('supports multiple documents through the orchestrator with collision-safe names',async()=>{const registry=new RendererRegistry();registerJpegRenderer(registry,new Rasterizer(1),new Encoder());const result=await new ExportOrchestrator({registry,resolveDocument:async(_t,id)=>({...document,documentGroupId:id})}).export({format:'JPEG',templateId:'jpeg',documentGroupIds:['a','b'],fileName:'same',options:{jpeg:{dpi:96}}});expect(result.files.map(file=>file.fileName)).toEqual(['same_page_001.jpg','same_page_001_2.jpg']);});
it('cancels between raster and encoding',async()=>{const source=new ExportCancellationSource();await expect(new JpegRenderer(new Rasterizer(2,()=>source.cancel()),new Encoder()).render({document,fileName:'cancel',options:{jpeg:{dpi:96}},cancellationToken:source.token})).rejects.toBeInstanceOf(ExportCancelledError);});
it('enforces the shared memory guard',async()=>{await expect(new JpegRenderer(new Rasterizer(1),new Encoder()).render({document,fileName:'large',options:{jpeg:{dpi:600,maxPixels:100}},cancellationToken:token})).rejects.toThrow(/Reduce DPI/);});
});
