import { describe,expect,it } from 'vitest';
import type { PhysicalPageRasterizer, RasterPage } from '../src/index.js';
import { estimateImageMemory, ImageSafetyError, PngRenderer, registerPngRenderer } from '../src/index.js';
import { ExportCancellationSource, ExportCancelledError, ExportOrchestrator, RendererRegistry } from '@document-tool/renderer-sdk';
import type { TemplateDefinition } from '@document-tool/contracts';

const template={id:'report',name:'Report',version:1,page:{size:'A4',orientation:'PORTRAIT',margins:{top:12,right:13,bottom:14,left:15},backgroundColor:'#ffffff',border:{enabled:true,style:'SOLID',width:1,color:'#000000'}},header:{blocks:[]},body:{blocks:[]},footer:{blocks:[]}} satisfies TemplateDefinition;
const document={documentGroupId:'group-1',template,model:{variables:{amount:'₹47.20',hiddenFreight:true},page:template.page,body:[]}};
class ExactFixtureRasterizer implements PhysicalPageRasterizer{calls:Array<{page:number;width:number;height:number;model:unknown}>=[];constructor(private count=2,private cancel?:()=>void){}async getPageCount(){return this.count;}async rasterizePage(resolved:typeof document,page:number,width:number,height:number):Promise<RasterPage>{this.calls.push({page,width,height,model:resolved.model});const rgba=new Uint8Array(width*height*4);rgba.fill(page?127:255);this.cancel?.();return{width,height,rgba};}}
function dimensions(bytes:Uint8Array){return{width:(bytes[16]!<<24)|(bytes[17]!<<16)|(bytes[18]!<<8)|bytes[19]!,height:(bytes[20]!<<24)|(bytes[21]!<<16)|(bytes[22]!<<8)|bytes[23]!};}
describe('Phase 4.19.2 PNG renderer',()=>{
  it('registers PNG and exports every physical page with deterministic names and geometry',async()=>{const rasterizer=new ExactFixtureRasterizer();const registry=new RendererRegistry();registerPngRenderer(registry,rasterizer);const result=await new ExportOrchestrator({registry,resolveDocument:async()=>document}).export({format:'PNG',templateId:'report',documentGroupIds:['group-1'],fileName:'report',options:{png:{dpi:96,pages:'ALL'}}});expect(registry.capabilities('PNG').supportsTransparency).toBe(true);expect(result.files.map(file=>file.fileName)).toEqual(['report_page_001.png','report_page_002.png']);expect(result.files.every(file=>file.bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10')).toBe(true);expect(dimensions(result.files[0]!.bytes)).toEqual({width:794,height:1123});expect(result.diagnostics).toMatchObject({format:'PNG',pageCount:2,dpi:96,fidelityVersion:'4.16'});expect(rasterizer.calls[0]!.model).toBe(document.model);});
  it('supports current-page export',async()=>{const rasterizer=new ExactFixtureRasterizer(3);const renderer=new PngRenderer(rasterizer);const result=await renderer.render({document,fileName:'letter',options:{png:{dpi:150,pages:'CURRENT',currentPage:2}},cancellationToken:{isCancellationRequested:false,throwIfCancellationRequested(){}}});expect(result.files[0]!.fileName).toBe('letter_page_002.png');expect(rasterizer.calls.map(call=>call.page)).toEqual([1]);});
  it('estimates physical memory independently from zoom and rejects unsafe pages',async()=>{expect(estimateImageMemory(210,297,300,1)).toMatchObject({width:2480,height:3508,pixelsPerPage:8699840});const renderer=new PngRenderer(new ExactFixtureRasterizer(1));await expect(renderer.render({document,fileName:'unsafe',options:{png:{dpi:600,maxPixels:1000}},cancellationToken:{isCancellationRequested:false,throwIfCancellationRequested(){}}})).rejects.toBeInstanceOf(ImageSafetyError);});
  it('cancels between physical pages',async()=>{const source=new ExportCancellationSource();const renderer=new PngRenderer(new ExactFixtureRasterizer(2,()=>source.cancel()));await expect(renderer.render({document,fileName:'cancel',options:{png:{dpi:96}},cancellationToken:source.token})).rejects.toBeInstanceOf(ExportCancelledError);});
  it('rejects non-preset DPI values',async()=>{const renderer=new PngRenderer(new ExactFixtureRasterizer(1));await expect(renderer.render({document,fileName:'bad',options:{png:{dpi:72}},cancellationToken:{isCancellationRequested:false,throwIfCancellationRequested(){}}})).rejects.toThrow(/Invalid PNG DPI/);});
});
