import { describe, expect, it } from 'vitest';
import type { TemplateDefinition } from '@document-tool/contracts';
import { CURRENT_WORKSPACE_SCHEMA_VERSION, LocalStorageTemplateRepository, WORKSPACE_BACKUP_FORMAT, WorkspacePersistenceError, type KeyValueStorage } from '../src/index.js';

class MemoryStorage implements KeyValueStorage{data=new Map<string,string>();getItem(key:string){return this.data.get(key)??null;}setItem(key:string,value:string){this.data.set(key,value);}removeItem(key:string){this.data.delete(key);}}
const template=(id='t1',name='ग्राहकाचे नाव ₹1,234.50'):TemplateDefinition=>({id,name,version:1,page:{size:'A4',orientation:'PORTRAIT',margins:{top:10,right:10,bottom:10,left:10}},header:{blocks:[]},body:{blocks:[]},footer:{blocks:[]},dataViews:[{id:'dv',name:'Freight Rows',alias:'freightRows',sourcePath:'items'}],calculatedFields:[]});

describe('Phase 5.0.5 workspace envelope and migration',()=>{
  it('migrates the legacy unversioned template array without loss',async()=>{const storage=new MemoryStorage();storage.setItem('document-tool.templates.v1',JSON.stringify([template()]));const repo=new LocalStorageTemplateRepository(storage);expect((await repo.list())[0]?.name).toContain('ग्राहकाचे');const saved=JSON.parse(storage.getItem('document-tool.templates.v1')!);expect(saved.schemaVersion).toBe(CURRENT_WORKSPACE_SCHEMA_VERSION);expect(saved.workspace.templates).toHaveLength(1);});
  it('writes centralized schema, app version, timestamp and increasing revision',async()=>{const storage=new MemoryStorage();const repo=new LocalStorageTemplateRepository(storage);await repo.save(template());const first=JSON.parse(storage.getItem('document-tool.templates.v1')!);await repo.save({...template(),name:'updated'});const second=JSON.parse(storage.getItem('document-tool.templates.v1')!);expect(first).toMatchObject({schemaVersion:1,appVersion:'1.0.0-rc.1',revision:1});expect(Date.parse(first.savedAt)).not.toBeNaN();expect(second.revision).toBeGreaterThan(first.revision);});
  it.each(['{bad json',JSON.stringify({templates:'wrong'})])('returns recovery instead of silently erasing corrupt data',raw=>{const storage=new MemoryStorage();storage.setItem('document-tool.templates.v1',raw);const result=new LocalStorageTemplateRepository(storage).inspect();expect(result.status).toBe('RECOVERY_REQUIRED');expect(storage.getItem('document-tool.templates.v1')).toBe(raw);});
  it('rejects future schema without mutation',async()=>{const storage=new MemoryStorage();const raw=JSON.stringify({schemaVersion:99,appVersion:'future',savedAt:new Date().toISOString(),revision:1,workspace:{templates:[template()]}});storage.setItem('document-tool.templates.v1',raw);await expect(new LocalStorageTemplateRepository(storage).list()).rejects.toMatchObject({code:'WORKSPACE_VERSION_TOO_NEW'});expect(storage.getItem('document-tool.templates.v1')).toBe(raw);});
});

describe('Phase 5.0.5 backup and safety',()=>{
  it('round-trips templates, Data Views, page setup and Unicode',async()=>{const first=new LocalStorageTemplateRepository(new MemoryStorage());await first.save(template());const backup=first.exportBackup();expect(backup.format).toBe(WORKSPACE_BACKUP_FORMAT);const second=new LocalStorageTemplateRepository(new MemoryStorage());await second.importBackup(JSON.stringify(backup));expect(await second.list()).toEqual(await first.list());});
  it('invalid backup never replaces current workspace',async()=>{const storage=new MemoryStorage();const repo=new LocalStorageTemplateRepository(storage);await repo.save(template());const before=storage.getItem('document-tool.templates.v1');await expect(repo.importBackup('{bad')).rejects.toBeInstanceOf(WorkspacePersistenceError);expect(storage.getItem('document-tool.templates.v1')).toBe(before);});
  it('serializes rapid saves so the last edit wins',async()=>{const repo=new LocalStorageTemplateRepository(new MemoryStorage());await Promise.all([repo.save(template('same','A')),repo.save(template('same','B')),repo.save(template('same','C'))]);expect((await repo.list())[0]?.name).toBe('C');});
  it('reset is explicit and recovery copy remains available before it',async()=>{const storage=new MemoryStorage();storage.setItem('document-tool.templates.v1','broken');const repo=new LocalStorageTemplateRepository(storage);expect(repo.recoveryCopy()).toBe('broken');repo.reset();expect(repo.inspect().status).toBe('EMPTY');});
});
