import { describe,expect,it } from 'vitest';
import type { DocumentGroup,TemplateDefinition } from '@document-tool/contracts';
import { TemplateEngine } from '../src/template-engine.js';
import { TemplateValidator } from '../src/template-validator.js';
const group:DocumentGroup={id:'g',key:'INV001',header:{invoice:{number:'INV001'},customer:{name:'ABC Ltd'}},items:[{product:'A',qty:2,rate:100}],itemDetails:[],sourceRowIndexes:[2],warnings:[],valid:true};
const base=():TemplateDefinition=>({id:'t',name:'T',version:1,page:{size:'A4',orientation:'PORTRAIT',margins:{top:10,right:10,bottom:10,left:10}},header:{blocks:[]},body:{blocks:[]},footer:{blocks:[]}});
describe('Phase 3.1 style validation',()=>{
 it('accepts offline fonts, valid sizes, hex, width, alignment and margins',()=>{const t=base();t.body.blocks=[{id:'x',type:'TEXT',text:'x',style:{fontFamily:'Arial',fontSize:6,textColor:'#000',backgroundColor:'#FFFFFF',alignment:'CENTER'},layout:{widthPercent:50,alignment:'RIGHT',marginTop:0}}];expect(new TemplateValidator().validate(t).valid).toBe(true);});
 it('rejects unsupported font and out of range font sizes',()=>{const t=base();t.body.blocks=[{id:'x',type:'TEXT',text:'x',style:{fontFamily:'Arial',fontSize:5}},{id:'y',type:'TEXT',text:'y',style:{fontFamily:'Arial',fontSize:97}}];const codes=new TemplateValidator().validate(t).errors.map(e=>e.code);expect(codes.filter(c=>c==='STYLE_FONT_SIZE_INVALID')).toHaveLength(2);});
 it('rejects invalid hex, width 0/101 and negative margins',()=>{const t=base();t.body.blocks=[{id:'x',type:'TEXT',text:'x',style:{textColor:'red'},layout:{widthPercent:0,marginTop:-1}},{id:'y',type:'TEXT',text:'y',layout:{widthPercent:101}}];const codes=new TemplateValidator().validate(t).errors.map(e=>e.code);expect(codes).toContain('STYLE_COLOR_INVALID');expect(codes.filter(c=>c==='BLOCK_WIDTH_INVALID')).toHaveLength(2);expect(codes).toContain('BLOCK_MARGIN_INVALID');});
});
describe('Phase 3.1 render model',()=>{
 it('preserves table layout, columns, header/cell style, border and padding',()=>{const t=base();t.body.blocks=[{id:'tb',type:'TABLE',sourcePath:'items',tableStyle:{widthPercent:50,alignment:'CENTER',headerStyle:{fontFamily:'Georgia',fontSize:11,bold:true,textColor:'#111111',backgroundColor:'#F3F4F6'},cellStyle:{fontFamily:'Arial',fontSize:9,textColor:'#222222'},border:{style:'DASHED',width:2,color:'#333333'},cellPadding:{top:1,right:2,bottom:3,left:4}},columns:[{id:'p',label:'Product',path:'product',widthPercent:50,alignment:'LEFT'},{id:'q',label:'Qty',path:'qty',widthPercent:20,alignment:'CENTER'},{id:'r',label:'Rate',path:'rate',widthPercent:30,alignment:'RIGHT'}]}];const b=new TemplateEngine().buildRenderModel(t,group).model?.body?.[0];expect(b).toMatchObject({type:'TABLE',widthPercent:50,alignment:'CENTER',border:{style:'DASHED',width:2,color:'#333333'},cellPadding:{top:1,right:2,bottom:3,left:4}});if(b?.type==='TABLE'){expect(b.columns.map(c=>c.widthPercent)).toEqual([50,20,30]);expect(b.columns.map(c=>c.alignment)).toEqual(['LEFT','CENTER','RIGHT']);expect(b.headerStyle).toMatchObject({fontFamily:'Georgia',bold:true,backgroundColor:'#F3F4F6'});expect(b.cellStyle).toMatchObject({fontFamily:'Arial',fontSize:9});}});
 it('preserves right table alignment',()=>{const t=base();t.body.blocks=[{id:'tb',type:'TABLE',sourcePath:'items',tableStyle:{widthPercent:75,alignment:'RIGHT'},columns:[{id:'p',label:'P',path:'product'}]}];expect(new TemplateEngine().buildRenderModel(t,group).model?.body?.[0]).toMatchObject({type:'TABLE',widthPercent:75,alignment:'RIGHT'});});
 it('rejects column width total over 100',()=>{const t=base();t.body.blocks=[{id:'tb',type:'TABLE',sourcePath:'items',columns:[{id:'a',label:'A',path:'product',widthPercent:70},{id:'b',label:'B',path:'qty',widthPercent:40}]}];expect(new TemplateValidator().validate(t).errors.some(e=>e.code==='TABLE_COLUMN_WIDTH_TOTAL_INVALID')).toBe(true);});
 it('preserves independent field styles, layouts and alignment',()=>{const t=base();t.body.blocks=[{id:'f',type:'FIELD',label:'Invoice No',path:'invoice.number',layoutMode:'STACKED',spacing:3,textAlignment:'RIGHT',layout:{widthPercent:50,alignment:'RIGHT'},labelStyle:{fontFamily:'Arial',fontSize:10,bold:true,textColor:'#666666'},valueStyle:{fontFamily:'Times New Roman',fontSize:12,italic:true,textColor:'#0000FF'}}];const b=new TemplateEngine().buildRenderModel(t,group).model?.body?.[0];expect(b).toMatchObject({type:'FIELD',layoutMode:'STACKED',spacing:3,textAlignment:'RIGHT',layout:{widthPercent:50,alignment:'RIGHT'},labelStyle:{fontFamily:'Arial',bold:true,textColor:'#666666'},valueStyle:{fontFamily:'Times New Roman',italic:true,textColor:'#0000FF'}});});
 it('supports inline field layout',()=>{const t=base();t.body.blocks=[{id:'f',type:'FIELD',label:'Invoice',path:'invoice.number',layoutMode:'INLINE'}];expect(new TemplateEngine().buildRenderModel(t,group).model?.body?.[0]).toMatchObject({type:'FIELD',layoutMode:'INLINE'});});
 it('accepts raster data images and preserves width/alignment/aspect',()=>{const t=base();t.body.blocks=[{id:'i',type:'IMAGE',sourceType:'DATA_URL',source:'data:image/png;base64,iVBORw0KGgo=',width:40,alignment:'CENTER',maintainAspectRatio:true}];const r=new TemplateEngine().buildRenderModel(t,group);expect(r.errors).toHaveLength(0);expect(r.model?.body?.[0]).toMatchObject({type:'IMAGE',width:40,alignment:'CENTER',maintainAspectRatio:true});});
 it('rejects remote or invalid image sources',()=>{const remote=base();remote.body.blocks=[{id:'i',type:'IMAGE',sourceType:'LOCAL_ASSET',source:'https://example.com/logo.png'}];expect(new TemplateValidator().validate(remote).errors.some(e=>e.code==='IMAGE_SOURCE_INVALID')).toBe(true);const bad=base();bad.body.blocks=[{id:'i',type:'IMAGE',sourceType:'DATA_URL',source:'data:image/svg+xml;base64,abc'}];expect(new TemplateValidator().validate(bad).errors.some(e=>e.code==='IMAGE_SOURCE_INVALID')).toBe(true);});
 it('keeps Phase 3 version-1 templates valid and resolves defaults',()=>{const old=base();old.body.blocks=[{id:'f',type:'FIELD',label:'Customer',path:'customer.name'},{id:'tb',type:'TABLE',sourcePath:'items',columns:[{id:'p',label:'Product',path:'product'}]}];const engine=new TemplateEngine();expect(engine.validate(old).valid).toBe(true);const r=engine.buildRenderModel(old,group);expect(r.errors).toHaveLength(0);expect(r.model?.body?.[0]).toMatchObject({type:'FIELD',layout:{widthPercent:100,alignment:'LEFT'}});expect(r.model?.body?.[1]).toMatchObject({type:'TABLE',widthPercent:100,alignment:'LEFT'});});
});
