import type { Artboard, DesignElement, DesignGroup, DesignTemplate, PathDesignElement, PathGeometry, ShapeDesignElement, TextDesignElement } from '@document-tool/contracts';
import { createBlankArtboard } from './artboards.js';

export type CartonStyle='STRAIGHT_TUCK_END'|'REVERSE_TUCK_END'|'STRAIGHT_TUCK_END_SLIT_LOCK'|'REVERSE_TUCK_END_SLIT_LOCK'|'SLEEVE';
export type CartonMeasurementBasis='INTERNAL'|'EXTERNAL';
export interface CartonDielineInput {style:CartonStyle;widthMm:number;depthMm:number;heightMm:number;materialThicknessMm:number;measurementBasis:CartonMeasurementBasis;glueFlapMm:number;tuckDepthMm:number;dustFlapMm:number;bleedMm:number;safeMarginMm:number;toleranceMm:number;}
export interface CartonPanel {id:string;name:'GLUE'|'FRONT'|'RIGHT'|'BACK'|'LEFT';xMm:number;yMm:number;widthMm:number;heightMm:number;rotationDeg:number;}
export type PackagingPanelKind='BODY'|'GLUE'|'TUCK'|'DUST';
export type PackagingPanelFace='FRONT'|'RIGHT'|'BACK'|'LEFT'|'GLUE';
export type PackagingPanelEdge='BODY'|'TOP'|'BOTTOM';
export interface PackagingPanel {id:string;name:string;kind:PackagingPanelKind;face:PackagingPanelFace;edge:PackagingPanelEdge;xMm:number;yMm:number;widthMm:number;heightMm:number;rotationDeg:number;artworkRotationDeg:number;safeMarginMm:number;bleedMm:number;printable:boolean;editable:boolean;coordinateSpace:'ARTBOARD';}
export interface CartonDielineValidationIssue {code:string;severity:'ERROR'|'WARNING';message:string;}
export interface CartonDielineMeasurements {flatWidthMm:number;flatHeightMm:number;cutWidthMm:number;cutHeightMm:number;bodyWidthMm:number;bodyDepthMm:number;bodyHeightMm:number;panels:CartonPanel[];packagingPanels:PackagingPanel[];}
export interface GeneratedCartonDieline {template:DesignTemplate;measurements:CartonDielineMeasurements;issues:CartonDielineValidationIssue[];}

export const DEFAULT_CARTON_DIELINE_INPUT:Readonly<CartonDielineInput>=Object.freeze({style:'STRAIGHT_TUCK_END',widthMm:70,depthMm:30,heightMm:110,materialThicknessMm:.45,measurementBasis:'INTERNAL',glueFlapMm:15,tuckDepthMm:24,dustFlapMm:18,bleedMm:3,safeMarginMm:4,toleranceMm:.3});
export const CARTON_STYLE_OPTIONS:readonly {id:CartonStyle;label:string;family:string}[]=[
 {id:'STRAIGHT_TUCK_END',label:'Straight Tuck End',family:'ECMA-style folding carton'},
 {id:'REVERSE_TUCK_END',label:'Reverse Tuck End',family:'ECMA-style folding carton'},
 {id:'STRAIGHT_TUCK_END_SLIT_LOCK',label:'Straight Tuck End · Slit Lock',family:'ECMA-style folding carton'},
 {id:'REVERSE_TUCK_END_SLIT_LOCK',label:'Reverse Tuck End · Slit Lock',family:'ECMA-style folding carton'},
 {id:'SLEEVE',label:'Simple Sleeve',family:'ECMA-style sleeve'}
];

export function validateCartonDielineInput(input:CartonDielineInput):CartonDielineValidationIssue[]{const issues:CartonDielineValidationIssue[]=[];const positive:[keyof CartonDielineInput,string][]=[['widthMm','Width'],['depthMm','Depth'],['heightMm','Height'],['materialThicknessMm','Material thickness'],['glueFlapMm','Glue flap'],['bleedMm','Bleed'],['safeMarginMm','Safe margin'],['toleranceMm','Tolerance']];for(const [key,label] of positive){const value=input[key];if(typeof value!=='number'||!Number.isFinite(value)||value<0||(key!=='bleedMm'&&key!=='toleranceMm'&&value===0))issues.push({code:`INVALID_${String(key).toUpperCase()}`,severity:'ERROR',message:`${label} must be a valid positive dimension.`});}if(input.widthMm<10||input.depthMm<5||input.heightMm<10)issues.push({code:'BOX_TOO_SMALL',severity:'ERROR',message:'Finished box must be at least 10 × 5 × 10 mm.'});if(input.materialThicknessMm>5)issues.push({code:'CALIPER_OUT_OF_RANGE',severity:'ERROR',message:'Material thickness above 5 mm is outside this folding-carton generator.'});if(input.glueFlapMm<input.materialThicknessMm*4)issues.push({code:'GLUE_FLAP_TOO_NARROW',severity:'ERROR',message:'Glue flap must be at least four times material thickness.'});if(input.glueFlapMm>input.widthMm*.75)issues.push({code:'GLUE_FLAP_LARGE',severity:'WARNING',message:'Glue flap is unusually wide relative to the front panel.'});if(input.style!=='SLEEVE'&&(input.tuckDepthMm<=0||input.tuckDepthMm>input.heightMm*.75))issues.push({code:'TUCK_DEPTH_INVALID',severity:'ERROR',message:'Tuck depth must be positive and no more than 75% of box height.'});if(input.style!=='SLEEVE'&&(input.dustFlapMm<=0||input.dustFlapMm>input.widthMm))issues.push({code:'DUST_FLAP_INVALID',severity:'ERROR',message:'Dust flap must be positive and no wider than the front panel.'});if(input.safeMarginMm*2>=Math.min(input.widthMm,input.heightMm))issues.push({code:'SAFE_AREA_INVALID',severity:'ERROR',message:'Safe margin leaves no usable artwork area.'});return issues;}

function adjusted(input:CartonDielineInput){const compensation=input.measurementBasis==='INTERNAL'?input.materialThicknessMm:0;return{width:input.widthMm+compensation*2,depth:input.depthMm+compensation*2,height:input.heightMm+compensation};}
export function calculateCartonDieline(input:CartonDielineInput):CartonDielineMeasurements{const body=adjusted(input),flap=input.style==='SLEEVE'?0:Math.max(input.tuckDepthMm,input.dustFlapMm),cutWidth=input.glueFlapMm+2*(body.width+body.depth),cutHeight=body.height+2*flap,pad=input.bleedMm+10,bodyY=flap;const starts=[0,input.glueFlapMm,input.glueFlapMm+body.width,input.glueFlapMm+body.width+body.depth,input.glueFlapMm+2*body.width+body.depth];const panels:CartonPanel[]=[{id:'glue',name:'GLUE',xMm:0,yMm:bodyY,widthMm:input.glueFlapMm,heightMm:body.height,rotationDeg:0},{id:'front',name:'FRONT',xMm:starts[1]!,yMm:bodyY,widthMm:body.width,heightMm:body.height,rotationDeg:0},{id:'right',name:'RIGHT',xMm:starts[2]!,yMm:bodyY,widthMm:body.depth,heightMm:body.height,rotationDeg:0},{id:'back',name:'BACK',xMm:starts[3]!,yMm:bodyY,widthMm:body.width,heightMm:body.height,rotationDeg:0},{id:'left',name:'LEFT',xMm:starts[4]!,yMm:bodyY,widthMm:body.depth,heightMm:body.height,rotationDeg:0}];const packagingPanels:PackagingPanel[]=[];for(const panel of panels){packagingPanels.push({id:`body-${panel.id}`,name:panel.name,kind:panel.name==='GLUE'?'GLUE':'BODY',face:panel.name,edge:'BODY',xMm:panel.xMm+pad,yMm:panel.yMm+pad,widthMm:panel.widthMm,heightMm:panel.heightMm,rotationDeg:0,artworkRotationDeg:0,safeMarginMm:input.safeMarginMm,bleedMm:input.bleedMm,printable:panel.name!=='GLUE',editable:panel.name!=='GLUE',coordinateSpace:'ARTBOARD'});}if(input.style!=='SLEEVE'){const reverse=input.style.startsWith('REVERSE');const faces=panels.filter((panel):panel is CartonPanel&{name:'FRONT'|'RIGHT'|'BACK'|'LEFT'}=>panel.name!=='GLUE');faces.forEach(panel=>{const topTuck=panel.name===(reverse?'BACK':'FRONT');const bottomTuck=panel.name===(reverse?'FRONT':'BACK');const topDepth=topTuck?input.tuckDepthMm:input.dustFlapMm;const bottomDepth=bottomTuck?input.tuckDepthMm:input.dustFlapMm;packagingPanels.push({id:`top-${panel.id}`,name:`TOP ${panel.name}${topTuck?' TUCK':' DUST'}`,kind:topTuck?'TUCK':'DUST',face:panel.name,edge:'TOP',xMm:panel.xMm+pad,yMm:bodyY-topDepth+pad,widthMm:panel.widthMm,heightMm:topDepth,rotationDeg:0,artworkRotationDeg:180,safeMarginMm:input.safeMarginMm,bleedMm:input.bleedMm,printable:true,editable:true,coordinateSpace:'ARTBOARD'});packagingPanels.push({id:`bottom-${panel.id}`,name:`BOTTOM ${panel.name}${bottomTuck?' TUCK':' DUST'}`,kind:bottomTuck?'TUCK':'DUST',face:panel.name,edge:'BOTTOM',xMm:panel.xMm+pad,yMm:bodyY+body.height+pad,widthMm:panel.widthMm,heightMm:bottomDepth,rotationDeg:0,artworkRotationDeg:0,safeMarginMm:input.safeMarginMm,bleedMm:input.bleedMm,printable:true,editable:true,coordinateSpace:'ARTBOARD'});});}return{flatWidthMm:cutWidth+2*pad,flatHeightMm:cutHeight+2*pad,cutWidthMm:cutWidth,cutHeightMm:cutHeight,bodyWidthMm:body.width,bodyDepthMm:body.depth,bodyHeightMm:body.height,panels,packagingPanels};}

type Pt={x:number;y:number};
function geometry(points:readonly Pt[],closed:boolean):PathGeometry{const nodes=points.map((p,index)=>({id:`p${index}`,x:p.x,y:p.y,mode:'CORNER' as const}));const count=closed?nodes.length:nodes.length-1;return{points:nodes,segments:Array.from({length:count},(_,index)=>({id:`s${index}`,type:'LINE' as const,fromPointId:nodes[index]!.id,toPointId:nodes[(index+1)%nodes.length]!.id})),closed};}
function path(id:string,name:string,points:readonly Pt[],closed:boolean,color:string,widthMm:number,style:PathDesignElement['stroke']['style'],zIndex:number,metadata:Record<string,unknown>):PathDesignElement{const xs=points.map(p=>p.x),ys=points.map(p=>p.y),minX=Math.min(...xs),minY=Math.min(...ys),maxX=Math.max(...xs),maxY=Math.max(...ys),local=points.map(p=>({x:p.x-minX,y:p.y-minY}));return{id,type:'PATH',name,position:{xMm:minX,yMm:minY},size:{widthMm:Math.max(.001,maxX-minX),heightMm:Math.max(.001,maxY-minY)},rotationDeg:0,opacity:1,visible:true,locked:true,zIndex,geometry:geometry(local,closed),fill:{type:'NONE'},stroke:{color,widthMm,style,dashArray:style==='DASHED'?[3,2]:undefined},metadata};}
function guideShape(id:string,name:string,x:number,y:number,w:number,h:number,color:string,zIndex:number,kind:string,visible=true):ShapeDesignElement{return{id,type:'SHAPE',name,position:{xMm:x,yMm:y},size:{widthMm:w,heightMm:h},rotationDeg:0,opacity:1,visible,locked:true,zIndex,shape:'RECTANGLE',fill:{type:'NONE'},stroke:{color,widthMm:.2,style:'DASHED',dashArray:[2,1]},metadata:{technicalLayer:kind,nonPrintingGuide:kind!=='CUT'&&kind!=='CREASE'}};}
function label(id:string,value:string,x:number,y:number,w:number,h:number,zIndex:number):TextDesignElement{return{id,type:'TEXT',name:`${value} Panel Label`,position:{xMm:x,yMm:y},size:{widthMm:w,heightMm:h},rotationDeg:0,opacity:.65,visible:true,locked:true,zIndex,text:value,style:{fontFamily:'Arial',fontSizePt:7,fontWeight:700,italic:false,underline:false,color:'#475569',alignment:'CENTER',lineHeight:1,letterSpacingPt:.5},metadata:{technicalLayer:'ANNOTATION',nonPrintingGuide:true}};}

function outlinePoints(input:CartonDielineInput,m:CartonDielineMeasurements,pad:number):Pt[]{const y=m.cutHeightMm===m.bodyHeightMm?0:(m.cutHeightMm-m.bodyHeightMm)/2,bodyBottom=y+m.bodyHeightMm,x=[0,input.glueFlapMm,input.glueFlapMm+m.bodyWidthMm,input.glueFlapMm+m.bodyWidthMm+m.bodyDepthMm,input.glueFlapMm+2*m.bodyWidthMm+m.bodyDepthMm,m.cutWidthMm],topDepth=input.style==='SLEEVE'?[0,0,0,0,0]:[0,input.tuckDepthMm,input.dustFlapMm,input.style.startsWith('REVERSE')?input.dustFlapMm:input.tuckDepthMm,input.dustFlapMm],bottomDepth=input.style==='SLEEVE'?[0,0,0,0,0]:[0,input.style.startsWith('REVERSE')?input.dustFlapMm:input.tuckDepthMm,input.dustFlapMm,input.style.startsWith('REVERSE')?input.tuckDepthMm:input.dustFlapMm,input.dustFlapMm];const points:Pt[]=[{x:x[0]!+pad,y:y+pad},{x:x[1]!+pad,y:y+pad}];for(let i=1;i<5;i++){points.push({x:x[i]!+pad,y:y-topDepth[i]!+pad},{x:x[i+1]!+pad,y:y-topDepth[i]!+pad});}points.push({x:x[5]!+pad,y:bodyBottom+bottomDepth[4]!+pad});for(let i=4;i>=1;i--){points.push({x:x[i]!+pad,y:bodyBottom+bottomDepth[i]!+pad},{x:x[i-1]!+pad,y:bodyBottom+bottomDepth[Math.max(0,i-1)]!+pad});}return points;}

export function generateCartonDieline(input:CartonDielineInput,ids:(prefix:string)=>string=prefix=>`${prefix}-${crypto.randomUUID()}`,identity?:{templateId?:string;artboardId?:string}):GeneratedCartonDieline{const issues=validateCartonDielineInput(input);if(issues.some(issue=>issue.severity==='ERROR'))throw new Error(issues.filter(issue=>issue.severity==='ERROR').map(issue=>issue.message).join(' '));const m=calculateCartonDieline(input),pad=input.bleedMm+10,artboard:Artboard=createBlankArtboard({id:identity?.artboardId??ids('carton-artboard'),name:`${CARTON_STYLE_OPTIONS.find(item=>item.id===input.style)?.label??input.style} Dieline`,order:0,widthMm:m.flatWidthMm,heightMm:m.flatHeightMm,background:{type:'SOLID',color:'#ffffff',opacity:1}});artboard.print={bleed:{topMm:0,rightMm:0,bottomMm:0,leftMm:0},safeArea:{topMm:0,rightMm:0,bottomMm:0,leftMm:0},minimumRasterDpi:150,preferredRasterDpi:300};const elements:DesignElement[]=[],groups:DesignGroup[]=[];const addGroup=(name:string,items:DesignElement[],locked=true,visible=true)=>{const groupId=ids(`dieline-${name.toLowerCase()}`);items.forEach(item=>{item.groupId=groupId;item.visible=visible;elements.push(item);});groups.push({id:groupId,name,elementIds:items.map(item=>item.id),locked,visible});};
 const cutMeta={technicalLayer:'CUT',technicalInkName:'DIELINE CUT',lineMeaning:'die-cut',printPolicy:'PROOF_ONLY'};const cuts:DesignElement[]=[path(ids('cut-contour'),'CUT · Continuous Outer Contour',outlinePoints(input,m,pad),true,'#e11d48',.3,'SOLID',100,cutMeta)];
 if(input.style.includes('SLIT_LOCK')){const y=(m.cutHeightMm-m.bodyHeightMm)/2+pad;cuts.push(path(ids('slit-top'),'CUT · Top Slit Lock',[{x:input.glueFlapMm+m.bodyWidthMm*.35+pad,y:y+pad*.05},{x:input.glueFlapMm+m.bodyWidthMm*.65+pad,y:y+pad*.05}],false,'#e11d48',.3,'SOLID',101,{...cutMeta,cutFeature:'SLIT_LOCK'}));}
 addGroup('CUT',cuts);
 const creaseMeta={technicalLayer:'CREASE',technicalInkName:'DIELINE CREASE',lineMeaning:'fold-score',printPolicy:'PROOF_ONLY'},creases:DesignElement[]=[];for(const panel of m.panels.slice(1)){creases.push(path(ids('crease-v'),`CREASE · ${panel.name} Start`,[{x:panel.xMm+pad,y:(m.cutHeightMm-m.bodyHeightMm)/2+pad},{x:panel.xMm+pad,y:(m.cutHeightMm+m.bodyHeightMm)/2+pad}],false,'#2563eb',.25,'DASHED',110,creaseMeta));}if(input.style!=='SLEEVE'){const y=(m.cutHeightMm-m.bodyHeightMm)/2;creases.push(path(ids('crease-top'),'CREASE · Top Fold',[{x:input.glueFlapMm+pad,y:y+pad},{x:m.cutWidthMm+pad,y:y+pad}],false,'#2563eb',.25,'DASHED',110,creaseMeta),path(ids('crease-bottom'),'CREASE · Bottom Fold',[{x:input.glueFlapMm+pad,y:y+m.bodyHeightMm+pad},{x:m.cutWidthMm+pad,y:y+m.bodyHeightMm+pad}],false,'#2563eb',.25,'DASHED',110,creaseMeta));}addGroup('CREASE',creases);
 const bleed=[guideShape(ids('bleed'),'BLEED · Artwork Extension',pad-input.bleedMm,pad-input.bleedMm,m.cutWidthMm+2*input.bleedMm,m.cutHeightMm+2*input.bleedMm,'#16a34a',90,'BLEED',false)];addGroup('BLEED',bleed,true,false);
 const safe:DesignElement[]=m.panels.filter(panel=>panel.name!=='GLUE').map(panel=>guideShape(ids('safe'),`SAFE · ${panel.name}`,panel.xMm+pad+input.safeMarginMm,panel.yMm+pad+input.safeMarginMm,Math.max(.1,panel.widthMm-2*input.safeMarginMm),Math.max(.1,panel.heightMm-2*input.safeMarginMm),'#f59e0b',80,'SAFE',true));addGroup('SAFE',safe);
 const annotations:DesignElement[]=m.panels.map(panel=>label(ids('label'),panel.name,panel.xMm+pad,panel.yMm+pad+panel.heightMm/2-3,panel.widthMm,6,120));addGroup('ANNOTATION',annotations);
 artboard.elements=elements;artboard.groups=groups;artboard.metadata={cartonDieline:{version:3,input:structuredClone(input),measurements:structuredClone(m),packagingPanels:structuredClone(m.packagingPanels),artworkGroups:{version:1,groups:m.packagingPanels.filter(panel=>panel.editable).map(panel=>({id:`artwork-${panel.id}`,panelId:panel.id,name:`${panel.name} Artwork`,elementIds:[]}))},standardFamily:'ECMA-style folding carton',certificationStatus:'UNVERIFIED_CONVERTER_APPROVAL_REQUIRED'},technicalLayers:['CUT','CREASE','BLEED','SAFE','ANNOTATION']};const design:DesignTemplate={kind:'CARD_DESIGN',schemaVersion:1,id:identity?.templateId??ids('carton-template'),name:`${CARTON_STYLE_OPTIONS.find(item=>item.id===input.style)?.label??'Carton'} · ${input.widthMm} × ${input.depthMm} × ${input.heightMm} mm`,version:1,status:'DRAFT',artboards:[artboard],sharedAssets:[],metadata:{cartonDieline:true,editable:true,requiresConverterApproval:true}};return{template:design,measurements:m,issues};}

export function cartonDielineInputFromTemplate(template:DesignTemplate):CartonDielineInput|undefined{const value=template.artboards[0]?.metadata?.cartonDieline;if(typeof value!=='object'||value===null)return undefined;const input=(value as Record<string,unknown>).input;return typeof input==='object'&&input!==null?structuredClone(input as CartonDielineInput):undefined;}

export function packagingPanelsFromArtboard(artboard:Artboard):PackagingPanel[]{const value=artboard.metadata?.cartonDieline;if(typeof value!=='object'||value===null)return[];const record=value as Record<string,unknown>;const direct=record.packagingPanels;if(Array.isArray(direct))return structuredClone(direct as PackagingPanel[]);const measurements=record.measurements;if(typeof measurements==='object'&&measurements!==null){const panels=(measurements as Record<string,unknown>).packagingPanels;if(Array.isArray(panels))return structuredClone(panels as PackagingPanel[]);}const input=record.input;if(typeof input==='object'&&input!==null){try{return calculateCartonDieline(input as CartonDielineInput).packagingPanels;}catch{return[];}}return[];}
