import type { DesignElement, DesignGroup, DesignTemplate, PathDesignElement, PathGeometry, PathPoint, PathSegment } from '@document-tool/contracts';
import type { PackagingPanel, PackagingPanelEdge, PackagingPanelFace, PackagingPanelKind } from './cartonDieline.js';
import { packagingPanelsFromArtboard } from './cartonDieline.js';
import { createBlankArtboard } from './artboards.js';
import { refreshPackagingArtworkIndex } from './packagingArtwork.js';

export type ImportedDielineLayer='CUT'|'CREASE'|'OTHER';
export type ManualPackagingPanelRole=
 |'FRONT'|'BACK'|'LEFT'|'RIGHT'|'GLUE'
 |'TOP_FRONT'|'TOP_BACK'|'TOP_LEFT'|'TOP_RIGHT'
 |'BOTTOM_FRONT'|'BOTTOM_BACK'|'BOTTOM_LEFT'|'BOTTOM_RIGHT';
export interface SvgDielineImportIssue {code:string;severity:'WARNING'|'ERROR';message:string;}
export interface SvgDielineImportResult {widthMm:number;heightMm:number;elements:PathDesignElement[];issues:SvgDielineImportIssue[];sourceViewBox:{x:number;y:number;width:number;height:number};}

const MM_PER_PX=25.4/96;
function lengthMm(raw:string|undefined,pxFallback=true):number|undefined{
 if(!raw)return undefined;const m=raw.trim().match(/^(-?\d*\.?\d+(?:e[-+]?\d+)?)\s*(mm|cm|in|pt|pc|px)?$/i);if(!m)return undefined;
 const v=Number(m[1]);if(!Number.isFinite(v))return undefined;const u=(m[2]||'px').toLowerCase();
 if(u==='mm')return v;if(u==='cm')return v*10;if(u==='in')return v*25.4;if(u==='pt')return v*25.4/72;if(u==='pc')return v*25.4/6;if(u==='px'&&pxFallback)return v*MM_PER_PX;return undefined;
}
function attrs(tag:string):Record<string,string>{const out:Record<string,string>={};for(const m of tag.matchAll(/([:\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g))out[m[1]!.toLowerCase()]=m[2]??m[3]??'';return out;}
function nums(raw:string|undefined):number[]{return (raw??'').trim().split(/[ ,]+/).map(Number).filter(Number.isFinite);}
function inferLayer(a:Record<string,string>):ImportedDielineLayer{const semantic=`${a.id??''} ${a.class??''} ${a['data-layer']??''} ${a['inkscape:label']??''}`.toLowerCase();if(/crease|fold|score/.test(semantic))return'CREASE';if(/\bcut\b|knife|die[-_ ]?cut/.test(semantic))return'CUT';return'OTHER';}
function pointKey(x:number,y:number){return `${x.toFixed(7)},${y.toFixed(7)}`;}
function geometryFromCommands(commands:{kind:'M'|'L'|'C'|'Z';values:number[]}[],sx:number,sy:number,ox:number,oy:number):PathGeometry|null{
 const points:PathPoint[]=[];const segments:PathSegment[]=[];const byCoord=new Map<string,string>();let current:string|undefined,start:string|undefined,closed=false,pi=0,si=0;
 const addPoint=(x:number,y:number)=>{const X=(x-ox)*sx,Y=(y-oy)*sy,key=pointKey(X,Y);let id=byCoord.get(key);if(!id){id=`p${pi++}`;points.push({id,x:X,y:Y,mode:'CORNER'});byCoord.set(key,id);}return id;};
 for(const c of commands){if(c.kind==='M'){current=addPoint(c.values[0]!,c.values[1]!);if(!start)start=current;continue;}if(c.kind==='Z'){if(current&&start&&current!==start)segments.push({id:`s${si++}`,type:'LINE',fromPointId:current,toPointId:start});closed=true;current=start;continue;}const to=addPoint(c.values[c.values.length-2]!,c.values[c.values.length-1]!);if(!current){current=to;if(!start)start=to;continue;}if(c.kind==='C'){
   const from=points.find(p=>p.id===current)!;const target=points.find(p=>p.id===to)!;from.outHandle={x:(c.values[0]!-ox)*sx,y:(c.values[1]!-oy)*sy};target.inHandle={x:(c.values[2]!-ox)*sx,y:(c.values[3]!-oy)*sy};segments.push({id:`s${si++}`,type:'CUBIC_BEZIER',fromPointId:current,toPointId:to});
  }else segments.push({id:`s${si++}`,type:'LINE',fromPointId:current,toPointId:to});current=to;
 }
 return points.length>=2?{points,segments,closed}:null;
}
function parsePathData(d:string,issues:SvgDielineImportIssue[]):{kind:'M'|'L'|'C'|'Z';values:number[]}[]{
 const tokens=[...d.matchAll(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:e[-+]?\d+)?/g)].map(m=>m[0]!);let i=0,cmd='',cx=0,cy=0,sx=0,sy=0;const out:{kind:'M'|'L'|'C'|'Z';values:number[]}[]=[];const n=()=>Number(tokens[i++]);
 while(i<tokens.length){if(/^[A-Za-z]$/.test(tokens[i]!))cmd=tokens[i++]!;if(!cmd)break;const rel=cmd===cmd.toLowerCase(),u=cmd.toUpperCase();
  if(u==='Z'){out.push({kind:'Z',values:[]});cx=sx;cy=sy;cmd='';continue;}
  if(u==='M'||u==='L'||u==='T'){const x=n(),y=n();if(!Number.isFinite(x)||!Number.isFinite(y))break;cx=rel?cx+x:x;cy=rel?cy+y:y;if(u==='M'){sx=cx;sy=cy;out.push({kind:'M',values:[cx,cy]});cmd=rel?'l':'L';}else out.push({kind:'L',values:[cx,cy]});continue;}
  if(u==='H'){const x=n();cx=rel?cx+x:x;out.push({kind:'L',values:[cx,cy]});continue;}if(u==='V'){const y=n();cy=rel?cy+y:y;out.push({kind:'L',values:[cx,cy]});continue;}
  if(u==='C'){const v=Array.from({length:6},n);if(v.some(x=>!Number.isFinite(x)))break;let [x1,y1,x2,y2,x,y]=v;if(rel){x1!+=cx;y1!+=cy;x2!+=cx;y2!+=cy;x!+=cx;y!+=cy;}out.push({kind:'C',values:[x1!,y1!,x2!,y2!,x!,y!]});cx=x!;cy=y!;continue;}
  if(u==='S'){const v=Array.from({length:4},n);if(v.some(x=>!Number.isFinite(x)))break;let [x2,y2,x,y]=v;if(rel){x2!+=cx;y2!+=cy;x!+=cx;y!+=cy;}out.push({kind:'C',values:[cx,cy,x2!,y2!,x!,y!]});cx=x!;cy=y!;issues.push({code:'SVG_SMOOTH_APPROX',severity:'WARNING',message:'Smooth cubic control was approximated during import.'});continue;}
  if(u==='Q'){const v=Array.from({length:4},n);if(v.some(x=>!Number.isFinite(x)))break;let [qx,qy,x,y]=v;if(rel){qx!+=cx;qy!+=cy;x!+=cx;y!+=cy;}const c1x=cx+2/3*(qx!-cx),c1y=cy+2/3*(qy!-cy),c2x=x!+2/3*(qx!-x!),c2y=y!+2/3*(qy!-y!);out.push({kind:'C',values:[c1x,c1y,c2x,c2y,x!,y!]});cx=x!;cy=y!;continue;}
  if(u==='A'){const v=Array.from({length:7},n);if(v.some(x=>!Number.isFinite(x)))break;let x=v[5]!,y=v[6]!;if(rel){x+=cx;y+=cy;}out.push({kind:'L',values:[x,y]});cx=x;cy=y;issues.push({code:'SVG_ARC_APPROX',severity:'WARNING',message:'SVG arc segments are imported as straight endpoints in this foundation release.'});continue;}
  issues.push({code:'SVG_COMMAND_UNSUPPORTED',severity:'WARNING',message:`Unsupported SVG path command ${cmd} was skipped.`});cmd='';
 }
 return out;
}
function normalizePathElement(id:string,name:string,geom:PathGeometry,layer:ImportedDielineLayer,zIndex:number):PathDesignElement{
 const xs=geom.points.flatMap(p=>[p.x,p.inHandle?.x,p.outHandle?.x].filter((x):x is number=>typeof x==='number')),ys=geom.points.flatMap(p=>[p.y,p.inHandle?.y,p.outHandle?.y].filter((y):y is number=>typeof y==='number'));const minX=Math.min(...xs),minY=Math.min(...ys),maxX=Math.max(...xs),maxY=Math.max(...ys);
 const shift=(p:{x:number;y:number})=>({x:p.x-minX,y:p.y-minY});const next:PathGeometry={...geom,points:geom.points.map(p=>({...p,...shift(p),inHandle:p.inHandle?shift(p.inHandle):undefined,outHandle:p.outHandle?shift(p.outHandle):undefined}))};const technical=layer==='OTHER'?undefined:layer;
 return{id,type:'PATH',name,position:{xMm:minX,yMm:minY},size:{widthMm:Math.max(.001,maxX-minX),heightMm:Math.max(.001,maxY-minY)},rotationDeg:0,opacity:1,visible:true,locked:false,zIndex,geometry:next,fill:{type:'NONE'},stroke:{color:layer==='CUT'?'#ef4444':layer==='CREASE'?'#2563eb':'#64748b',widthMm:.25,style:layer==='CREASE'?'DASHED':'SOLID',dashArray:layer==='CREASE'?[3,2]:undefined},metadata:{importedDieline:true,importedDielineLayer:layer,technicalLayer:technical,nonPrintingGuide:false}};
}
export function importSvgDieline(svg:string,idFactory:(prefix:string)=>string):SvgDielineImportResult{
 const issues:SvgDielineImportIssue[]=[];const root=svg.match(/<svg\b[^>]*>/i);if(!root)return{widthMm:0,heightMm:0,elements:[],issues:[{code:'SVG_ROOT_MISSING',severity:'ERROR',message:'SVG root element was not found.'}],sourceViewBox:{x:0,y:0,width:0,height:0}};const ra=attrs(root[0]);const vb=nums(ra.viewbox);let vx=0,vy=0,vw=vb[2]??0,vh=vb[3]??0;if(vb.length>=4){vx=vb[0]!;vy=vb[1]!;}let widthMm=lengthMm(ra.width),heightMm=lengthMm(ra.height);if(!vw||!vh){vw=widthMm?widthMm/MM_PER_PX:100;vh=heightMm?heightMm/MM_PER_PX:100;issues.push({code:'SVG_VIEWBOX_MISSING',severity:'WARNING',message:'SVG has no usable viewBox; physical scaling uses width/height fallback.'});}if(!widthMm){widthMm=vw*MM_PER_PX;issues.push({code:'SVG_WIDTH_ASSUMED_PX',severity:'WARNING',message:'SVG width has no physical unit; 96 DPI CSS pixel scaling was assumed.'});}if(!heightMm){heightMm=vh*MM_PER_PX;issues.push({code:'SVG_HEIGHT_ASSUMED_PX',severity:'WARNING',message:'SVG height has no physical unit; 96 DPI CSS pixel scaling was assumed.'});}const sx=widthMm/vw,sy=heightMm/vh;const elements:PathDesignElement[]=[];let z=10;
 const tags=[...svg.matchAll(/<(path|line|polyline|polygon|rect)\b[^>]*>/gi)];for(const match of tags){const tag=match[0]!,kind=match[1]!.toLowerCase(),a=attrs(tag);if(a.transform){issues.push({code:'SVG_TRANSFORM_UNSUPPORTED',severity:'WARNING',message:'An SVG transform attribute was found; transformed geometry should be visually verified after import.'});}const layer=inferLayer(a);let commands:{kind:'M'|'L'|'C'|'Z';values:number[]}[]=[];
  if(kind==='path')commands=parsePathData(a.d??'',issues);else if(kind==='line'){commands=[{kind:'M',values:[Number(a.x1??0),Number(a.y1??0)]},{kind:'L',values:[Number(a.x2??0),Number(a.y2??0)]}];}else if(kind==='rect'){const x=Number(a.x??0),y=Number(a.y??0),w=Number(a.width??0),h=Number(a.height??0);commands=[{kind:'M',values:[x,y]},{kind:'L',values:[x+w,y]},{kind:'L',values:[x+w,y+h]},{kind:'L',values:[x,y+h]},{kind:'Z',values:[]}];}else{const p=nums(a.points);for(let j=0;j+1<p.length;j+=2)commands.push({kind:j===0?'M':'L',values:[p[j]!,p[j+1]!]});if(kind==='polygon')commands.push({kind:'Z',values:[]});}
  const chunks:{kind:'M'|'L'|'C'|'Z';values:number[]}[][]=[];let current:{kind:'M'|'L'|'C'|'Z';values:number[]}[]=[];for(const command of commands){if(command.kind==='M'&&current.length){chunks.push(current);current=[];}current.push(command);}if(current.length)chunks.push(current);for(let sub=0;sub<chunks.length;sub++){const g=geometryFromCommands(chunks[sub]!,sx,sy,vx,vy);if(!g)continue;const base=a.id||`Imported ${kind} ${elements.length+1}`,name=chunks.length>1?`${base} ${sub+1}`:base;elements.push(normalizePathElement(idFactory('dieline-path'),name,g,layer,z++));}
 }
 if(!elements.length)issues.push({code:'SVG_NO_VECTOR_GEOMETRY',severity:'ERROR',message:'No supported vector path/line/polyline/polygon/rect geometry was found.'});return{widthMm,heightMm,elements,issues,sourceViewBox:{x:vx,y:vy,width:vw,height:vh}};
}
function ensureTechnicalGroup(groups:DesignGroup[],name:'CUT'|'CREASE',ids:string[]):DesignGroup[]{const existing=groups.find(g=>g.name===name);if(existing)return groups.map(g=>g.id===existing.id?{...g,elementIds:[...new Set([...g.elementIds,...ids])],locked:g.locked??false,visible:true}:g);return[...groups,{id:`import-${name.toLowerCase()}`,name,elementIds:ids,locked:false,visible:true}];}
export function assignImportedDielineLayer(template:DesignTemplate,artboardId:string,elementIds:readonly string[],layer:ImportedDielineLayer):DesignTemplate{return{...template,artboards:template.artboards.map(a=>{if(a.id!==artboardId)return a;const selected=new Set(elementIds);let groups=a.groups.map(g=>({...g,elementIds:g.elementIds.filter(id=>!selected.has(id)||!(g.name==='CUT'||g.name==='CREASE'))}));if(layer==='CUT'||layer==='CREASE')groups=ensureTechnicalGroup(groups,layer,[...selected]);const elements=a.elements.map(e=>!selected.has(e.id)?e:{...e,locked:false,stroke:e.type==='PATH'?{...e.stroke,color:layer==='CUT'?'#ef4444':layer==='CREASE'?'#2563eb':'#64748b',style:layer==='CREASE'?'DASHED':'SOLID',dashArray:layer==='CREASE'?[3,2]:undefined}:undefined,metadata:{...e.metadata,importedDieline:true,importedDielineLayer:layer,technicalLayer:layer==='OTHER'?undefined:layer,nonPrintingGuide:false}} as DesignElement);return{...a,elements,groups};})};}
function roleParts(role:ManualPackagingPanelRole,flapKind:'TUCK'|'DUST'='DUST'):{face:PackagingPanelFace;edge:PackagingPanelEdge;kind:PackagingPanelKind;name:string}{const p=role.split('_');if(p.length===1){const face=role as PackagingPanelFace;return{face,edge:'BODY',kind:face==='GLUE'?'GLUE':'BODY',name:face};}const edge=p[0] as 'TOP'|'BOTTOM',face=p[1] as PackagingPanelFace;return{face,edge,kind:flapKind,name:`${edge} ${face} ${flapKind}`};}
export function mapSelectionToPackagingPanel(template:DesignTemplate,artboardId:string,elementIds:readonly string[],role:ManualPackagingPanelRole,options:{safeMarginMm:number;bleedMm:number;flapKind?:'TUCK'|'DUST'}):DesignTemplate{
 const art=template.artboards.find(a=>a.id===artboardId);if(!art)return template;const chosen=art.elements.filter(e=>elementIds.includes(e.id));if(!chosen.length)return template;const minX=Math.min(...chosen.map(e=>e.position.xMm)),minY=Math.min(...chosen.map(e=>e.position.yMm)),maxX=Math.max(...chosen.map(e=>e.position.xMm+e.size.widthMm)),maxY=Math.max(...chosen.map(e=>e.position.yMm+e.size.heightMm));const parts=roleParts(role,options.flapKind),id=`manual-${role.toLowerCase().replaceAll('_','-')}`;const panel:PackagingPanel={id,name:parts.name,kind:parts.kind,face:parts.face,edge:parts.edge,xMm:minX,yMm:minY,widthMm:maxX-minX,heightMm:maxY-minY,rotationDeg:0,artworkRotationDeg:parts.edge==='TOP'?180:0,safeMarginMm:options.safeMarginMm,bleedMm:options.bleedMm,printable:parts.face!=='GLUE',editable:parts.face!=='GLUE',coordinateSpace:'ARTBOARD'};const existing=packagingPanelsFromArtboard(art).filter(p=>p.id!==id),panels=[...existing,panel];const carton=(art.metadata?.cartonDieline??{}) as Record<string,unknown>;const nextArt={...art,metadata:{...art.metadata,cartonDieline:{...carton,source:'IMPORTED_SVG',packagingPanels:panels,measurements:{...((carton.measurements??{}) as Record<string,unknown>),packagingPanels:panels}}}};const next={...template,artboards:template.artboards.map(a=>a.id===artboardId?nextArt:a)};return refreshPackagingArtworkIndex(next,artboardId,panels);
}
export function createSvgDielineArtboard(template:DesignTemplate,result:SvgDielineImportResult,artboardId:string,artboardName:string):DesignTemplate{
 const artboard=createBlankArtboard({id:artboardId,name:artboardName,order:0,widthMm:result.widthMm,heightMm:result.heightMm});
 artboard.elements=result.elements;artboard.metadata={cartonDieline:{version:2,source:'IMPORTED_SVG',import:{physicalWidthMm:result.widthMm,physicalHeightMm:result.heightMm,viewBox:result.sourceViewBox},packagingPanels:[]}};
 let groups:DesignGroup[]=[];const cuts=result.elements.filter(e=>e.metadata?.importedDielineLayer==='CUT').map(e=>e.id),creases=result.elements.filter(e=>e.metadata?.importedDielineLayer==='CREASE').map(e=>e.id);if(cuts.length)groups=ensureTechnicalGroup(groups,'CUT',cuts);if(creases.length)groups=ensureTechnicalGroup(groups,'CREASE',creases);artboard.groups=groups;return{...template,artboards:[artboard]};
}

export function lockImportedDielineTechnicalGeometry(template:DesignTemplate,artboardId:string,locked=true):DesignTemplate{return{...template,artboards:template.artboards.map(a=>{if(a.id!==artboardId)return a;const technicalIds=new Set(a.groups.filter(g=>g.name==='CUT'||g.name==='CREASE').flatMap(g=>g.elementIds));return{...a,groups:a.groups.map(g=>(g.name==='CUT'||g.name==='CREASE')?{...g,locked}:g),elements:a.elements.map(e=>technicalIds.has(e.id)?{...e,locked}:e)};})};}
