import type { IncomingMessage } from 'node:http';
import { ApiAuthenticationError, type ApiAuthenticator, type ApiPrincipal } from './auth.js';

export type GoogleAuthorizationGrant = {
  code: string;
  codeVerifier: string;
  redirectUri: string;
};

export class GoogleOAuthExchangeError extends Error {
  constructor(readonly status: number, readonly code: string, message: string) {
    super(message);
  }
}

/** Only allow the ephemeral loopback callback generated by the native desktop app. */
export function validateGoogleAuthorizationGrant(value: unknown): GoogleAuthorizationGrant {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new GoogleOAuthExchangeError(400, 'INVALID_OAUTH_REQUEST', 'Invalid Google authorization request.');
  }
  const input = value as Record<string, unknown>;
  const { code, codeVerifier, redirectUri } = input;
  if (typeof code !== 'string' || code.length < 1 || code.length > 2048 ||
      typeof codeVerifier !== 'string' || !/^[A-Za-z0-9._~-]{43,128}$/.test(codeVerifier) ||
      typeof redirectUri !== 'string') {
    throw new GoogleOAuthExchangeError(400, 'INVALID_OAUTH_REQUEST', 'Invalid Google authorization request.');
  }
  let callback: URL;
  try { callback = new URL(redirectUri); }
  catch { throw new GoogleOAuthExchangeError(400, 'INVALID_OAUTH_REDIRECT', 'Invalid desktop callback URL.'); }
  if (callback.protocol !== 'http:' || callback.hostname !== '127.0.0.1' ||
      !callback.port || Number(callback.port) < 1 || Number(callback.port) > 65535 ||
      callback.pathname !== '/callback' || callback.search || callback.hash ||
      callback.username || callback.password) {
    throw new GoogleOAuthExchangeError(400, 'INVALID_OAUTH_REDIRECT', 'Invalid desktop callback URL.');
  }
  return { code, codeVerifier, redirectUri };
}

export function createGoogleOAuthCodeExchanger(options: {
  clientId: string;
  clientSecret: string;
  authenticator: ApiAuthenticator;
  fetchImpl?: typeof fetch;
}): (grant: GoogleAuthorizationGrant) => Promise<ApiPrincipal> {
  const clientId = options.clientId.trim();
  const clientSecret = options.clientSecret.trim();
  if (!clientId || !clientSecret) throw new Error('Google OAuth exchange requires server-side client credentials.');
  const fetchImpl = options.fetchImpl ?? fetch;
  return async (grant) => {
    const verified = validateGoogleAuthorizationGrant(grant);
    let response: Response;
    try {
      response = await fetchImpl('https://oauth2.googleapis.com/token', {
        method: 'POST',
        headers: { 'content-type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          client_id: clientId,
          client_secret: clientSecret,
          code: verified.code,
          code_verifier: verified.codeVerifier,
          redirect_uri: verified.redirectUri,
          grant_type: 'authorization_code',
        }),
        signal: AbortSignal.timeout(10_000),
      });
    } catch {
      throw new GoogleOAuthExchangeError(502, 'GOOGLE_OAUTH_UNAVAILABLE', 'Google verification is temporarily unavailable.');
    }
    // Never return the upstream response body; it may contain sensitive information.
    if (!response.ok) {
      throw new GoogleOAuthExchangeError(401, 'GOOGLE_OAUTH_REJECTED', 'Google verification failed. Please sign in again.');
    }
    let token: unknown;
    try { token = (await response.json() as {id_token?:unknown}).id_token; }
    catch { /* handled below */ }
    if (typeof token !== 'string' || !token) {
      throw new GoogleOAuthExchangeError(502, 'GOOGLE_IDENTITY_MISSING', 'Google did not return a valid identity.');
    }
    try {
      const principal = await options.authenticator.authenticate({
        headers: { 'x-pdfdocgen-authorization': `Bearer ${token}` },
      } as unknown as IncomingMessage);
      if (principal.authType !== 'oidc') throw new ApiAuthenticationError();
      return principal;
    } catch (error) {
      if (error instanceof ApiAuthenticationError) {
        throw new GoogleOAuthExchangeError(401, 'GOOGLE_IDENTITY_REJECTED', error.message);
      }
      throw error;
    }
  };
}
