import { describe,expect,it } from 'vitest';
import type { AssetReference,DesignTemplate } from '@document-tool/contracts';
import { addAssetReference,addDesignElement,createBlankArtboard,createImageElement,createShapeElement,createTextElement,deleteDesignElements,nextElementZIndex,updateDesignElement,validateDesignTemplate } from '../src/index.js';

const fixture=():DesignTemplate=>({kind:'CARD_DESIGN',schemaVersion:1,id:'t',name:'T',version:1,status:'DRAFT',sharedAssets:[],artboards:[createBlankArtboard({id:'a',name:'Front',order:0,widthMm:90,heightMm:50})]});

describe('Phase 6.0.4 core elements',()=>{
 it('creates production defaults for text and shapes',()=>{const text=createTextElement({id:'text'}),shape=createShapeElement('ROUNDED_RECTANGLE',{id:'shape'});expect(text.type).toBe('TEXT');expect(text.style.fontSizePt).toBeGreaterThan(0);expect(shape.type).toBe('SHAPE');expect(shape.cornerRadiusMm).toBeGreaterThan(0);});
 it('supports transparent shape fill with an independent border',()=>{const shape={...createShapeElement('RECTANGLE',{id:'outline'}),fill:{type:'NONE'} as const,stroke:{color:'#111827',widthMm:.5,style:'SOLID' as const}};expect(shape.fill).toEqual({type:'NONE'});expect(shape.stroke.style).toBe('SOLID');expect(shape.stroke.widthMm).toBe(.5);});
 it('adds elements with deterministic z-index progression',()=>{let t=fixture();expect(nextElementZIndex(t,'a')).toBe(0);t=addDesignElement(t,'a',createTextElement({id:'one',zIndex:nextElementZIndex(t,'a')}));expect(nextElementZIndex(t,'a')).toBe(1);t=addDesignElement(t,'a',createShapeElement('STAR',{id:'two',zIndex:nextElementZIndex(t,'a')}));expect(t.artboards[0]!.elements.map(e=>e.zIndex)).toEqual([0,1]);});
 it('updates a typed element without renderer-side business logic',()=>{let t=addDesignElement(fixture(),'a',createTextElement({id:'text'}));t=updateDesignElement(t,'a','text',e=>e.type==='TEXT'?{...e,text:'Auraa Dreams',style:{...e.style,fontWeight:700}}:e);const e=t.artboards[0]!.elements[0]!;expect(e.type).toBe('TEXT');if(e.type==='TEXT'){expect(e.text).toBe('Auraa Dreams');expect(e.style.fontWeight).toBe(700);}});
 it('creates image elements only against shared assets',()=>{const asset:AssetReference={id:'asset',name:'Logo',kind:'LOGO',sourceType:'DATA_URL',source:'data:image/png;base64,AA==',mimeType:'image/png',widthPx:100,heightPx:50};let t=addAssetReference(fixture(),asset);t=addDesignElement(t,'a',createImageElement(asset.id,{id:'img'}));expect(validateDesignTemplate(t).valid).toBe(true);expect((t.artboards[0]!.elements[0] as any).maintainAspectRatio).toBe(true);});
 it('deletes selected unlocked elements but preserves locked elements',()=>{let t=fixture();const open=createShapeElement('RECTANGLE',{id:'open'});const locked={...createShapeElement('CIRCLE',{id:'locked'}),locked:true};t=addDesignElement(addDesignElement(t,'a',open),'a',locked);t=deleteDesignElements(t,'a',['open','locked']);expect(t.artboards[0]!.elements.map(e=>e.id)).toEqual(['locked']);});
});
