import { describe,expect,it } from 'vitest';
import type { DesignTemplate,ShapeDesignElement } from '@document-tool/contracts';
import { createBlankArtboard,emptySelection,getSelectionBounds,moveElements,normalizeRotationDeg,nudgeElements,resizeElement,rotateElement,selectAllSelectable,selectByMarquee,selectOnly,toggleSelection } from '../src/index.js';
const shape=(id:string,x:number,y:number,w=20,h=10,locked=false):ShapeDesignElement=>({id,type:'SHAPE',name:id,position:{xMm:x,yMm:y},size:{widthMm:w,heightMm:h},rotationDeg:0,opacity:1,visible:true,locked,zIndex:0,shape:'RECTANGLE',fill:{type:'SOLID',color:'#fff'},stroke:{color:'#000',widthMm:.2,style:'SOLID'}});
const fixture=():DesignTemplate=>({kind:'CARD_DESIGN',schemaVersion:1,id:'t',name:'T',version:1,status:'DRAFT',sharedAssets:[],artboards:[{...createBlankArtboard({id:'a',name:'Front',order:0,widthMm:90,heightMm:50}),elements:[shape('one',5,5),shape('two',35,10),shape('locked',70,5,10,10,true)]}]});
describe('Phase 6.0.3 selection and transform engine',()=>{
 it('supports single, toggle and selectable-all selection while excluding locked elements from select-all',()=>{const a=fixture().artboards[0]!;let s=selectOnly(a.id,'one');expect(s.elementIds).toEqual(['one']);s=toggleSelection(s,'two');expect(s.elementIds).toEqual(['one','two']);s=toggleSelection(s,'one');expect(s.elementIds).toEqual(['two']);expect(selectAllSelectable(a).elementIds).toEqual(['one','two']);});
 it('maintains deterministic primary selection while toggling individual elements',()=>{const a=fixture().artboards[0]!;let s=selectOnly(a.id,'one');s=toggleSelection(s,'two');expect(s).toMatchObject({elementIds:['one','two'],primaryElementId:'two'});s=toggleSelection(s,'one');expect(s).toMatchObject({elementIds:['two'],primaryElementId:'two'});s=toggleSelection(s,'two');expect(s.elementIds).toEqual([]);expect(s.primaryElementId).toBeUndefined();});
 it('marquee selection intersects visible unlocked element bounds',()=>{const a=fixture().artboards[0]!;const s=selectByMarquee(a,{xMm:0,yMm:0,widthMm:30,heightMm:30},'REPLACE',emptySelection(a.id));expect(s.elementIds).toEqual(['one']);});
 it('moves multi-selection but never transforms locked elements',()=>{let t=fixture();t=moveElements(t,'a',['one','locked'],{xMm:2,yMm:-1});const [one,,locked]=t.artboards[0]!.elements;expect(one!.position).toEqual({xMm:7,yMm:4});expect(locked!.position).toEqual({xMm:70,yMm:5});});
 it('resizes from an anchor with a minimum size and supports aspect ratio',()=>{let t=fixture();t=resizeElement(t,'a','one',{widthMm:40,heightMm:10},{anchor:'NW',maintainAspectRatio:true});const e=t.artboards[0]!.elements[0]!;expect(e.size.widthMm).toBe(40);expect(e.size.heightMm).toBe(20);expect(e.position.xMm).toBe(-15);expect(e.position.yMm).toBe(-5);t=resizeElement(t,'a','one',{widthMm:0,heightMm:0},{minSizeMm:.5});expect(t.artboards[0]!.elements[0]!.size.widthMm).toBeGreaterThanOrEqual(.5);});
 it('normalizes arbitrary rotations including negative and 360+',()=>{expect(normalizeRotationDeg(-90)).toBe(270);expect(normalizeRotationDeg(450)).toBe(90);let t=rotateElement(fixture(),'a','one',725);expect(t.artboards[0]!.elements[0]!.rotationDeg).toBe(5);});
 it('nudges by normal and large keyboard steps',()=>{let t=nudgeElements(fixture(),'a',['one'],'RIGHT');expect(t.artboards[0]!.elements[0]!.position.xMm).toBe(5.5);t=nudgeElements(t,'a',['one'],'DOWN',true);expect(t.artboards[0]!.elements[0]!.position.yMm).toBe(10);});
 it('computes deterministic selection bounds',()=>{const es=fixture().artboards[0]!.elements.slice(0,2);expect(getSelectionBounds(es)).toEqual({xMm:5,yMm:5,widthMm:50,heightMm:15});});
});
