import { describe,expect,it } from 'vitest';
import { DESIGN_STARTER_TEMPLATES,validateDesignTemplate } from '../src/index.js';

describe('Phase 9.2 professional editable template pack',()=>{
 it('covers all launch categories with gallery metadata',()=>{const categories=new Set(DESIGN_STARTER_TEMPLATES.map(item=>item.category));for(const category of ['ID Card','Business Card','Membership Card','Invitation','Greeting Card','Promotional Card','Product Label','Shipping Label','Hang Tag','Voucher','Certificate','Sticker Sheet','Menu & Tent','Packaging Panel'])expect(categories.has(category),category).toBe(true);for(const starter of DESIGN_STARTER_TEMPLATES){expect(starter.formatLabel.length).toBeGreaterThan(3);expect(starter.tags.length).toBeGreaterThan(0);expect(starter.previewColor).toMatch(/^#[0-9a-f]{6}$/i);}});
 it('creates contract-valid print-ready editable designs with named layers',()=>{for(const starter of DESIGN_STARTER_TEMPLATES){const design=starter.create(prefix=>`${starter.id}-${prefix}`);expect(validateDesignTemplate(design).errors,starter.name).toEqual([]);expect(design.metadata?.editable).toBe(true);expect(design.metadata?.printReadySample).toBe(true);for(const artboard of design.artboards){expect(artboard.elements.length).toBeGreaterThan(0);expect(artboard.elements.every(element=>element.name.trim().length>0)).toBe(true);expect(artboard.print.preferredRasterDpi).toBe(300);}}});
 it('pairs every two-sided sample as Front and Back',()=>{for(const starter of DESIGN_STARTER_TEMPLATES){const design=starter.create(prefix=>`${starter.id}-${prefix}`);if(design.artboards.length!==2)continue;const [front,back]=design.artboards;expect(front?.role,starter.name).toBe('FRONT');expect(back?.role,starter.name).toBe('BACK');expect(front?.pairId).toBeTruthy();expect(front?.pairId).toBe(back?.pairId);expect([front?.widthMm,front?.heightMm]).toEqual([back?.widthMm,back?.heightMm]);}});
 it('includes dynamic-field-ready templates',()=>{const bound=DESIGN_STARTER_TEMPLATES.filter(starter=>starter.create(prefix=>`${starter.id}-${prefix}`).artboards.some(artboard=>artboard.elements.some(element=>Boolean(element.bindings?.length))));expect(bound.length).toBeGreaterThanOrEqual(15);});
});
