import { describe,expect,it } from 'vitest';
import { CARTON_STYLE_OPTIONS,DEFAULT_CARTON_DIELINE_INPUT,calculateCartonDieline,cartonDielineInputFromTemplate,generateCartonDieline,validateCartonDielineInput,validateDesignTemplate,packagingPanelsFromArtboard } from '../src/index.js';

const ids=()=>{let value=0;return(prefix:string)=>`${prefix}-${++value}`;};

describe('Phase 9.3 parameterized carton dielines',()=>{
 it('supports the five initial folding-carton structures',()=>{expect(CARTON_STYLE_OPTIONS.map(item=>item.id)).toEqual(['STRAIGHT_TUCK_END','REVERSE_TUCK_END','STRAIGHT_TUCK_END_SLIT_LOCK','REVERSE_TUCK_END_SLIT_LOCK','SLEEVE']);});
 it('calculates deterministic compensated blank dimensions and panel mapping',()=>{const measurement=calculateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT);expect(measurement.bodyWidthMm).toBeCloseTo(70.9);expect(measurement.bodyDepthMm).toBeCloseTo(30.9);expect(measurement.bodyHeightMm).toBeCloseTo(110.45);expect(measurement.cutWidthMm).toBeCloseTo(218.6);expect(measurement.panels.map(panel=>panel.name)).toEqual(['GLUE','FRONT','RIGHT','BACK','LEFT']);expect(measurement.panels[1]?.widthMm).toBeCloseTo(measurement.bodyWidthMm);});
 it('generates a contract-valid continuous cut contour and independent creases',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());expect(validateDesignTemplate(generated.template).errors).toEqual([]);const artboard=generated.template.artboards[0]!,cut=artboard.elements.find(element=>element.metadata?.technicalLayer==='CUT'&&element.type==='PATH');expect(cut?.type).toBe('PATH');if(cut?.type==='PATH'){expect(cut.geometry.closed).toBe(true);expect(cut.geometry.segments).toHaveLength(cut.geometry.points.length);}expect(artboard.elements.filter(element=>element.metadata?.technicalLayer==='CREASE').length).toBeGreaterThanOrEqual(6);expect(artboard.groups.map(group=>group.name)).toEqual(['CUT','CREASE','BLEED','SAFE','ANNOTATION']);expect(artboard.metadata?.cartonDieline).toBeTruthy();expect(generated.measurements.packagingPanels.some(panel=>panel.id==='body-front'&&panel.face==='FRONT'&&panel.coordinateSpace==='ARTBOARD')).toBe(true);expect(packagingPanelsFromArtboard(artboard)).toEqual(generated.measurements.packagingPanels);});
 it('marks proof-only and non-printing technical content explicitly',()=>{const artboard=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids()).template.artboards[0]!;for(const element of artboard.elements){const layer=element.metadata?.technicalLayer;expect(['CUT','CREASE','BLEED','SAFE','ANNOTATION']).toContain(layer);if(layer==='CUT'||layer==='CREASE')expect(element.metadata?.printPolicy).toBe('PROOF_ONLY');else expect(element.metadata?.nonPrintingGuide).toBe(true);}expect(artboard.groups.find(group=>group.name==='BLEED')?.visible).toBe(false);});
 it('upgrades Phase 9.3 metadata to canonical packaging panels on read',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());const artboard=generated.template.artboards[0]!;const meta=structuredClone(artboard.metadata!);const carton=(meta.cartonDieline as Record<string,unknown>);delete carton.packagingPanels;const measurements=carton.measurements as Record<string,unknown>;delete measurements.packagingPanels;const legacy={...artboard,metadata:meta};expect(packagingPanelsFromArtboard(legacy).some(panel=>panel.id==='body-front')).toBe(true);});
 it('creates semantic top and bottom panels for tuck cartons',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());const panels=generated.measurements.packagingPanels;expect(panels.filter(panel=>panel.edge==='TOP')).toHaveLength(4);expect(panels.filter(panel=>panel.edge==='BOTTOM')).toHaveLength(4);expect(panels.some(panel=>panel.kind==='TUCK')).toBe(true);expect(panels.some(panel=>panel.kind==='DUST')).toBe(true);});
 it('round-trips generator input through template metadata',()=>{const generated=generateCartonDieline({...DEFAULT_CARTON_DIELINE_INPUT,style:'REVERSE_TUCK_END',widthMm:82},ids());expect(cartonDielineInputFromTemplate(generated.template)).toEqual({...DEFAULT_CARTON_DIELINE_INPUT,style:'REVERSE_TUCK_END',widthMm:82});});
 it('rejects unsafe dimensions and warns about unusual glue flaps',()=>{expect(validateCartonDielineInput({...DEFAULT_CARTON_DIELINE_INPUT,widthMm:0}).some(issue=>issue.severity==='ERROR')).toBe(true);expect(()=>generateCartonDieline({...DEFAULT_CARTON_DIELINE_INPUT,tuckDepthMm:100},ids())).toThrow();expect(validateCartonDielineInput({...DEFAULT_CARTON_DIELINE_INPUT,glueFlapMm:60}).some(issue=>issue.code==='GLUE_FLAP_LARGE')).toBe(true);});
 it('generates sleeve geometry without horizontal flap creases',()=>{const generated=generateCartonDieline({...DEFAULT_CARTON_DIELINE_INPUT,style:'SLEEVE'},ids()),artboard=generated.template.artboards[0]!;expect(generated.measurements.cutHeightMm).toBeCloseTo(generated.measurements.bodyHeightMm);expect(artboard.elements.filter(element=>element.name.includes('Top Fold')||element.name.includes('Bottom Fold'))).toHaveLength(0);});
});
