import { describe,expect,it } from 'vitest';
import { DEFAULT_CARTON_DIELINE_INPUT,assignElementsToPackagingPanel,createImageElement,createTextElement,fitElementsToPackagingPanel,generateCartonDieline,packagingArtworkPanelId,prepareElementForPackagingPanel,validatePackagingArtwork } from '../src/index.js';

const ids=()=>{let value=0;return(prefix:string)=>`${prefix}-${++value}`;};

describe('Phase 9.4D-F packaging artwork operations',()=>{
 it('creates persistent virtual artwork groups for editable panels',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());const carton=generated.template.artboards[0]!.metadata?.cartonDieline as Record<string,unknown>;const index=carton.artworkGroups as {groups:Array<{panelId:string}>};expect(index.groups.length).toBe(generated.measurements.packagingPanels.filter(panel=>panel.editable).length);expect(index.groups.some(group=>group.panelId==='body-front')).toBe(true);});
 it('assigns content to a panel without consuming normal DesignGroup membership',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());const panel=generated.measurements.packagingPanels.find(item=>item.id==='body-front')!;const text=createTextElement({id:'art-text',name:'Headline',xMm:panel.xMm+10,yMm:panel.yMm+10,zIndex:200});let template={...generated.template,artboards:generated.template.artboards.map(a=>({...a,elements:[...a.elements,text]}))};template=assignElementsToPackagingPanel(template,template.artboards[0]!.id,[text.id],panel,generated.measurements.packagingPanels);const assigned=template.artboards[0]!.elements.find(item=>item.id===text.id)!;expect(packagingArtworkPanelId(assigned)).toBe(panel.id);expect(assigned.groupId).toBeUndefined();});
 it('fit/contain centers artwork and bleed fill marks backgrounds',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());const artboard=generated.template.artboards[0]!,panel=generated.measurements.packagingPanels.find(item=>item.id==='body-front')!;const image=prepareElementForPackagingPanel(createImageElement('asset',{id:'image',name:'Hero',xMm:0,yMm:0,widthMm:20,heightMm:10,zIndex:200}),panel);let template={...generated.template,sharedAssets:[{id:'asset',name:'Hero',kind:'IMAGE' as const,sourceType:'EMBEDDED' as const,source:'x',widthPx:200,heightPx:100}],artboards:[{...artboard,elements:[...artboard.elements,image]}]};template=fitElementsToPackagingPanel(template,artboard.id,[image.id],panel,generated.measurements.packagingPanels,'CONTAIN',template.sharedAssets);const contained=template.artboards[0]!.elements.find(item=>item.id===image.id)!;expect(contained.position.xMm).toBeGreaterThanOrEqual(panel.xMm-.01);expect(contained.position.yMm).toBeGreaterThanOrEqual(panel.yMm-.01);template=fitElementsToPackagingPanel(template,artboard.id,[image.id],panel,generated.measurements.packagingPanels,'BLEED_FILL',template.sharedAssets);const bleed=template.artboards[0]!.elements.find(item=>item.id===image.id)!;expect(bleed.position.xMm).toBeCloseTo(panel.xMm-panel.bleedMm);expect(bleed.metadata?.packagingArtworkRole).toBe('BACKGROUND');});
 it('warns when critical content leaves safe area and when a background misses bleed',()=>{const generated=generateCartonDieline(DEFAULT_CARTON_DIELINE_INPUT,ids());const artboard=generated.template.artboards[0]!,panel=generated.measurements.packagingPanels.find(item=>item.id==='body-front')!;const text=prepareElementForPackagingPanel(createTextElement({id:'text',name:'Headline',xMm:panel.xMm,yMm:panel.yMm,zIndex:200}),panel);const bg=prepareElementForPackagingPanel(createImageElement('asset',{id:'bg',name:'Background',xMm:panel.xMm,yMm:panel.yMm,widthMm:panel.widthMm,heightMm:panel.heightMm,zIndex:199}),panel,'BACKGROUND');const issues=validatePackagingArtwork({...artboard,elements:[...artboard.elements,text,bg]},generated.measurements.packagingPanels);expect(issues.some(issue=>issue.code==='SAFE_AREA'&&issue.elementId==='text')).toBe(true);expect(issues.some(issue=>issue.code==='BLEED_COVERAGE'&&issue.elementId==='bg')).toBe(true);});
});
