import {describe,expect,it} from 'vitest';
import type {Artboard,PathDesignElement} from '@document-tool/contracts';
import {localToWorld,materializeStraightPathIntersections,resolvePointSnap} from '../src/index.js';

function line(id:string,a:{x:number;y:number},b:{x:number;y:number}):PathDesignElement{const minX=Math.min(a.x,b.x),minY=Math.min(a.y,b.y),p1=`${id}-a`,p2=`${id}-b`;return{id,type:'PATH',name:id,position:{xMm:minX,yMm:minY},size:{widthMm:Math.max(.1,Math.abs(b.x-a.x)),heightMm:Math.max(.1,Math.abs(b.y-a.y))},rotationDeg:0,opacity:1,visible:true,locked:false,zIndex:1,geometry:{points:[{id:p1,x:a.x-minX,y:a.y-minY,mode:'CORNER'},{id:p2,x:b.x-minX,y:b.y-minY,mode:'CORNER'}],segments:[{id:`${id}-s`,type:'LINE',fromPointId:p1,toPointId:p2}],closed:false},fill:{type:'NONE'},stroke:{style:'SOLID',color:'#000',widthMm:.5}};}
function board(elements:PathDesignElement[]):Artboard{return{id:'a',name:'A',order:0,widthMm:100,heightMm:100,displayUnit:'MM',background:{type:'SOLID',color:'#fff',opacity:1},print:{bleed:{topMm:0,rightMm:0,bottomMm:0,leftMm:0},safeArea:{topMm:0,rightMm:0,bottomMm:0,leftMm:0}},guides:[],groups:[],elements};}

describe('persistent CAD intersection nodes',()=>{
 it('splits both crossing straight segments at one canonical coordinate',()=>{const horizontal=line('h',{x:0,y:10},{x:20,y:10}),vertical=line('v',{x:10,y:0},{x:10,y:20}),result=materializeStraightPathIntersections([horizontal,vertical],['v']) as PathDesignElement[];for(const element of result){expect(element.geometry.segments).toHaveLength(2);const ids=element.metadata?.intersectionNodeIds as string[];expect(ids).toHaveLength(1);const point=element.geometry.points.find(item=>item.id===ids[0])!;expect(localToWorld(point,element)).toEqual({x:10,y:10});}});
 it('materializes endpoint-to-segment T-junctions without adding a connector',()=>{const base=line('base',{x:0,y:10},{x:20,y:10}),branch=line('branch',{x:10,y:0},{x:10,y:10}),result=materializeStraightPathIntersections([base,branch],['branch']) as PathDesignElement[];expect(result[0]!.geometry.segments).toHaveLength(2);expect(result[1]!.geometry.segments).toHaveLength(1);expect(result[1]!.metadata?.intersectionNodeIds).toContain('branch-b');});
 it('returns declared intersections ahead of ordinary endpoint/vertex snaps',()=>{const elements=materializeStraightPathIntersections([line('h',{x:0,y:10},{x:20,y:10}),line('v',{x:10,y:0},{x:10,y:20})],['v']) as PathDesignElement[];const snap=resolvePointSnap(board(elements),{x:10.04,y:10.03},{toleranceMm:.2,lineStart:{x:0,y:0}});expect(snap).toMatchObject({kind:'INTERSECTION',label:'Intersection',point:{x:10,y:10}});});
 it('consolidates a fan of nearby endpoints onto the existing declared intersection',()=>{const master=line('master',{x:0,y:0},{x:10,y:10});master.metadata={intersectionNodeIds:['master-b']};const a=line('a',{x:10.08,y:10.03},{x:20,y:0}),b=line('b',{x:9.94,y:10.09},{x:20,y:20}),c=line('c',{x:10.12,y:9.96},{x:10,y:20}),result=materializeStraightPathIntersections([master,a,b,c],['c']) as PathDesignElement[];for(const element of result){const closest=element.geometry.points.map(point=>localToWorld(point,element)).sort((left,right)=>Math.hypot(left.x-10,left.y-10)-Math.hypot(right.x-10,right.y-10))[0]!;expect(closest.x).toBe(10);expect(closest.y).toBe(10);}});
 it('closes a near endpoint-to-segment gap and splits the target at the projected junction',()=>{const base=line('base',{x:0,y:10},{x:20,y:10}),branch=line('branch',{x:10,y:0},{x:10.08,y:9.88}),result=materializeStraightPathIntersections([base,branch],['branch']) as PathDesignElement[];expect(result[0]!.geometry.segments).toHaveLength(2);const branchEnd=result[1]!.geometry.points.find(point=>point.id==='branch-b')!;expect(localToWorld(branchEnd,result[1]!)).toEqual({x:10.08,y:10});});
});
