import {describe,expect,it} from 'vitest';
import type {PathDesignElement} from '@document-tool/contracts';
import {createShapeElement,findJoinedLineRegionAtPoint} from '../src/index.js';

function line(id:string,ax:number,ay:number,bx:number,by:number):PathDesignElement{const a=`${id}-a`,b=`${id}-b`;return{id,type:'PATH',name:id,position:{xMm:0,yMm:0},size:{widthMm:Math.max(.1,Math.abs(bx-ax)),heightMm:Math.max(.1,Math.abs(by-ay))},rotationDeg:0,opacity:1,visible:true,locked:false,zIndex:1,geometry:{points:[{id:a,x:ax,y:ay,mode:'CORNER'},{id:b,x:bx,y:by,mode:'CORNER'}],segments:[{id:`${id}-s`,type:'LINE',fromPointId:a,toPointId:b}],closed:false},fill:{type:'NONE'},stroke:{style:'SOLID',color:'#000',widthMm:.5}};}

describe('joined straight-line regions',()=>{
 it('creates a closed face from separate point-connected LINE paths',()=>{const elements=[line('top',10,10,30,10),line('right',30,10,30,30),line('bottom',30,30,10,30),line('left',10,30,10,10)];const region=findJoinedLineRegionAtPoint(elements,{x:20,y:20});expect(region?.geometry.closed).toBe(true);expect(region?.geometry.points).toHaveLength(4);expect(region?.sourceElementIds).toHaveLength(4);expect(region?.areaMm2).toBeCloseTo(400,6);});
 it('accepts endpoints merged within CAD tolerance and rejects an open graph',()=>{const almost=[line('a',0,0,10,0),line('b',10.03,0,10,10),line('c',10,10,0,10),line('d',0,10,0,0)];expect(findJoinedLineRegionAtPoint(almost,{x:5,y:5})).toBeDefined();expect(findJoinedLineRegionAtPoint(almost.slice(0,3),{x:5,y:5})).toBeUndefined();});
 it('selects the smallest enclosed face under the click',()=>{const outer=[line('o1',0,0,20,0),line('o2',20,0,20,20),line('o3',20,20,0,20),line('o4',0,20,0,0)],inner=[line('i1',5,5,10,5),line('i2',10,5,10,10),line('i3',10,10,5,10),line('i4',5,10,5,5)];expect(findJoinedLineRegionAtPoint([...outer,...inner],{x:7,y:7})?.areaMm2).toBeCloseTo(25,6);});
 it('uses a curved circle boundary plus an internal polyline as independent faces',()=>{const circle=createShapeElement('CIRCLE',{id:'circle',name:'Circle',xMm:0,yMm:0,widthMm:40,heightMm:40,zIndex:1}),diameter=line('diameter',20,0,20,40);const left=findJoinedLineRegionAtPoint([circle,diameter],{x:10,y:20}),right=findJoinedLineRegionAtPoint([circle,diameter],{x:30,y:20});expect(left).toBeDefined();expect(right).toBeDefined();expect(left?.sourceElementIds.sort()).toEqual(['circle','diameter']);expect(left!.areaMm2).toBeLessThan(700);expect(left!.areaMm2).toBeGreaterThan(550);expect(right!.areaMm2).toBeCloseTo(left!.areaMm2,4);});
 it('selects a nested internal compartment instead of the containing parent shape',()=>{const circle=createShapeElement('CIRCLE',{id:'circle',name:'Circle',xMm:0,yMm:0,widthMm:40,heightMm:40,zIndex:1}),diamond=[line('d1',20,4,34,20),line('d2',34,20,20,36),line('d3',20,36,6,20),line('d4',6,20,20,4)];const center=findJoinedLineRegionAtPoint([circle,...diamond],{x:20,y:20});expect(center).toBeDefined();expect(center!.areaMm2).toBeCloseTo(448,6);expect(center!.sourceElementIds).not.toContain('circle');});
});
