import {describe,expect,it} from 'vitest';
import type {PathDesignElement} from '@document-tool/contracts';
import {splitClosedElementByDivider,splitComponentFaceByDivider} from '../src/index.js';

function line(id:string,a:{x:number;y:number},b:{x:number;y:number}):PathDesignElement{const minX=Math.min(a.x,b.x),minY=Math.min(a.y,b.y),p1=`${id}-a`,p2=`${id}-b`;return{id,type:'PATH',name:id,position:{xMm:minX,yMm:minY},size:{widthMm:Math.max(.1,Math.abs(b.x-a.x)),heightMm:Math.max(.1,Math.abs(b.y-a.y))},rotationDeg:0,opacity:1,visible:true,locked:false,zIndex:4,geometry:{points:[{id:p1,x:a.x-minX,y:a.y-minY,mode:'CORNER'},{id:p2,x:b.x-minX,y:b.y-minY,mode:'CORNER'}],segments:[{id:`${id}-s`,type:'LINE',fromPointId:p1,toPointId:p2}],closed:false},fill:{type:'NONE'},stroke:{style:'SOLID',color:'#000',widthMm:.5}};}
function triangle():PathDesignElement{const points=[{id:'top',x:20,y:0,mode:'CORNER' as const},{id:'right',x:40,y:40,mode:'CORNER' as const},{id:'left',x:0,y:40,mode:'CORNER' as const}];return{id:'triangle',type:'PATH',name:'Triangle',position:{xMm:0,yMm:0},size:{widthMm:40,heightMm:40},rotationDeg:0,opacity:1,visible:true,locked:false,zIndex:1,geometry:{points,segments:[{id:'tr',type:'LINE',fromPointId:'top',toPointId:'right'},{id:'rl',type:'LINE',fromPointId:'right',toPointId:'left'},{id:'lt',type:'LINE',fromPointId:'left',toPointId:'top'}],closed:true},fill:{type:'SOLID',color:'#3b82f6'},stroke:{style:'SOLID',color:'#000',widthMm:.5}};}

describe('T-junction automatic multi-section topology',()=>{
 it('clips a long crossing LINE to the closed face entry and exit intersections',()=>{const cut=line('long',{x:-10,y:20},{x:50,y:20});const faces=splitClosedElementByDivider(triangle(),cut,'component');expect(faces).toHaveLength(2);expect(faces?.every(face=>face.geometry.closed&&face.groupId==='component')).toBe(true);});
 it('then accepts a boundary-to-shared-divider T-junction and yields three independent faces',()=>{const first=line('horizontal',{x:-10,y:20},{x:50,y:20}),faces=splitClosedElementByDivider(triangle(),first,'component')!;expect(faces).toHaveLength(2);const second=line('vertical',{x:20,y:0},{x:20,y:20}),split=splitComponentFaceByDivider(faces,second,'component',faces.map(face=>face.id));expect(split).toBeDefined();const resulting=[...faces.filter(face=>face.id!==split!.sourceId),...split!.faces];expect(resulting).toHaveLength(3);expect(resulting.every(face=>face.geometry.closed&&face.metadata?.faceGeneration==='AUTO_SECTION')).toBe(true);});
 it('still rejects a line that crosses the boundary only once',()=>{expect(splitClosedElementByDivider(triangle(),line('one',{x:-10,y:20},{x:20,y:20}),'component')).toBeUndefined();});
});
